### ISSUE TITLE
Processor: Singular, Plural, or Both?

### ISSUE THREAD

**Issue by dbwiddis** [dblock/oshi#102]
See #28 for previous discussion relevant to this topic.

I'm working on a long-awaited refactoring (See #46) to be more consistent with our package/class names.  Since this will require a major version bump, this is also an appropriate time to revisit our treatment of Processor(s).  I keep having great ideas of separating out System vs. Processor-specific code, and then go to implement and find that it's just not that easy to do.  Here's the long and short of it:

The current implementation has a separate object for each processor. Most of the stuff is identical/redundant system-based code for which I've used a lot of `static` code to get to work.  The only things which are individual processor specific are:
* Processor number.  
   * This is just an index, anyway.
* Vendor, Name, Identifier, Stepping, Model, Family, Frequency, 64-bit
   * While technically these are pulled individually from each processor on Windows (from registry) and Linux (from /proc/cpuinfo) the fact is that these are all identical (and all come from the same single String on OS X).  Also, it's not really truthful to represent that my MacBook Pro has 8 Intel i7 chips... in fact, I only have 1 quad core (hyperthreaded) processor.
* CPU load tick counters
   * These are the truly unique bits of data for each (logical) processor.  However, the code to retrieve the tick counts calls all processors simultaneously (returning an 8x4 array on my system).  On OS X there is no choice -- an array is returned from the system.  Similarly on Linux all cpu's are parsed from a single read of /proc/stat.  Windows could theoretically have multiple individiual PDH counters.  Implementing this on a per-processor basis would require inefficient duplication (read all processors and only retrieve one, repeat) and/or a lot of extra overhead (separate PDH objects for each processor counter). More importantly, reading per-processor ticks individually would give inconsistent results: the sum of all individual processors would not necessarily add to system usage, if a different processor was under different load when the call was made at a later time.  So I'm strongly in favor of keeping the current "read all the processors at once" methodology.

I am leaning strongly in favor of dropping the individual processor objects in favor of a singular CentralProcessor object.  Objects that return per-processor information would simply return an array.  This would offer the following advantages:
* Eliminate most/all of my `static` code since we'll now have one 'proper' CPU object
* Simplify API access to systemwide statistics (no need to pull an array, check for nonzero length, and pull system info from an arbitrary (usually 0) processor)
* Simplify API access to per-processor statistics (instead of iterating the array of processors to pull ticks from each one, simply return the array of ticks (which is its internal representation anyway) directly)
* More accurately represent system architecture (one quad-core i7 cpu, not 8 of them)

Disadvantages of making CentralProcessor singular:
* Removes the potential on Windows/Linux for different processors in a single package (is this actually common, likely, or useful, to mix different chip types in a true dual-cpu sytem?)
* Forces us to return "all" individual processor info instead of just one (but for reasons explained above this is desired for cpu load/tick counts and the most likely use case will be iterating all processors anyway)

**Comment by phoenixjiangnan** [comment]
Can you please add this to the wiki page? We are upgrading from 1.5.2 to 2.0 and I got totally confused on the missing getProcessors() method. I'm assuming some others might have run into this situation as well. Thanks!

**Comment by dbwiddis** [comment]
Can you clarify specifically where you'd like it added?  I did write [UPGRADING.md](https://github.com/dblock/oshi/blob/master/UPGRADING.md) which I thought covered it, but I see now I didn't discuss the change to HAL's `getProcessors()`.

Would fixing UPGRADING work, or should it also be in the README?

**Comment by phoenixjiangnan** [comment]
Add UPGRADING.md, RELASING.md, and other md files to README would be great! Also there's a wiki page https://github.com/dblock/oshi/wiki here you can take advantage of.

Again, I highly appreciate you guys' work for us to use it easily :)
