### ISSUE TITLE
Monitor (Screen) information

### ISSUE THREAD

**Issue by blizzardengle** [dblock/oshi#106]
Is there any possibility that support for detecting and gathering detailed information about all attached monitors (screens) will be added?

**Comment by dbwiddis** [comment]
There is certainly a possibility. That could be increased to a probability with some more specifics. What specific info is desired?  Are you aware of any other code that does what you want?

**Comment by dbwiddis** [comment]
Also, what functionality is desired that is not already in the [GraphicsDevice](https://docs.oracle.com/javase/7/docs/api/java/awt/GraphicsDevice.html) class?

**Comment by blizzardengle** [comment]
There is no Java code that can do what I'm looking for. There is only work arounds that call a C++, C#, VBS, or Powershell script for Windows. You again need to call other scripts for Mac OS and Linux based OS's. The main goal is to link what Java can find to what the system (computer) has recorded as the setup; I'm referring to this as determining each attached monitors "MAC address".

Example: With Java's GraphicsEnvironment you can get a monitors number, width, height, refresh rate, and bit depth. See this code for a full explanation: http://kodejava.org/how-do-i-get-screens-display-mode-information/

Problem: If you call getIDstring() on the above referenced code you will get something like this; assuming you have 3 monitors attached.

\.\Display0
\.\Display1
\.\Display2

0 is the primary monitor (usually), 1 and 2 can actually switch every time you turn on your computer or plug a new monitor in. This means if you are running a Java app that needs to automatically setup frames and information on specific monitors you can't. There is no way to know what monitor is Display1 or Display2.

The closest I have seen anyone get on this issue is here: http://stackoverflow.com/questions/10237937/looking-for-a-reliable-mapping-of-forms-screen-devicename-to-monitor-edid-info

If you look at the sample output on the accepted answer you will notice they get something very similar to what Java would return. If you can get another script to return Display0, Display1, Display2 you can now link up which monitor Display0, Display1, Display2 is actually referring to in Java.

BONUS: There are other scripts as well that could really help network admins out. This can return every bit of information possible from the EDID. Monitors manufacture, year of manufacture, week or manufacture, serial number, and so on. If you could add this to Oshi it would be a network admins all in one dream.

**Comment by dbwiddis** [comment]
Excellent. Thanks for those links... it looks like Windows provides the APIs (described in the above links) to enable this functionality.  

My initial intention will be for Oshi to return an array of objects corresponding to the Windows [DISPLAY_DEVICE](https://msdn.microsoft.com/en-us/library/dd183569(v=vs.85).aspx) structure, possibly with a method that returns the corresponding GraphicsDevice class.  I may modify this based on what OS X and Linux provide.

**Comment by dbwiddis** [comment]
Note to self:  use [CoreGraphics API](https://developer.apple.com/library/mac/documentation/GraphicsImaging/Reference/Quartz_Services_Ref/index.html#//apple_ref/c/func/CGGetOnlineDisplayList) for OS X

**Comment by dbwiddis** [comment]
Note to self:  try [xrandr](https://github.com/mehmetmertyildiran/xrandr-verbose-output/blob/master/output.txt) for Linux.  May be possible programmatically using X library.

**Comment by dbwiddis** [comment]
Well, getting the `DISPLAY_DEVICE` info was relatively easy:
```
Device Name: \\.\DISPLAY1\Monitor0
Device String: Generic PnP Monitor
Device State Flags: 11
Device ID: \\?\DISPLAY#DEL4014#4&1d20dce1&0&UID16843008#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
Device Key: \Registry\Machine\System\CurrentControlSet\Control\Class\{4d36e96e-e325-11ce-bfc1-08002be10318}\0003

Device Name: \\.\DISPLAY3\Monitor0
Device String: Generic PnP Monitor
Device State Flags: 11
Device ID: \\?\DISPLAY#DEL4026#5&15d6765b&0&UID1078018#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
Device Key: \Registry\Machine\System\CurrentControlSet\Control\Class\{4d36e96e-e325-11ce-bfc1-08002be10318}\0002
```

Unfortunately I'm hitting a roadblock using the SetupAPI to get additional information... is the info given enough for you, or do I need to hunt down a correlation to something else?

**Comment by blizzardengle** [comment]
That is a great start! You work fast. Take a look at this post though: http://blogs.technet.com/b/heyscriptingguy/archive/2013/10/03/use-powershell-to-discover-multi-monitor-information.aspx 

I still can't find the original example that I found but you have to parse the data your getting and it will turn into something like this:

Manufacture: Dell
Model: 1234
Serial Number 1234 (or empty for some manufactures)
Physical Width: 16"
Physical Height: 9"
Resolution: 1900 x 800 x 32
Bit Depth: 32
Type: LCD (CRT...and so on)

The list is actually longer but I'm still looking for the one I found before. You can even detect as well if and which monitors are plugging into a dedicated graphics card.

My main issue though is still with Device Name. See how you have Display1 and Display3. Java natively still only returns Display0 and Display1. It simply counts up. Your registry for example could have Display6, Display17, and Display19 for your attached monitors and from my understanding Java does not see this relationship like this:

Display0 ---> Display6
Display1 ---> Display17
Display2 ---> Display19

One day Java could see the relationship like this and another day it could be different:

Display0 ---> Display19
Display1 ---> Display6
Display2 ---> Display17

Again that is from my limited understanding and tests. I won't have time to research this more for a while.

**Comment by dbwiddis** [comment]
Making progress slowly, but may be way out of my league here.  I can successfully query the [EDID](https://en.wikipedia.org/wiki/Extended_Display_Identification_Data) info (A 128-byte array) for the monitors using the [SetupDiEnumDeviceInfo](https://msdn.microsoft.com/en-us/library/windows/hardware/ff551010(v=vs.85).aspx) .  I've parsed a bit of the EDID... there's more available, of course...
```
Manufacturer ID/Model: DEL4014
Resolution: 1280x1024 @ 75 Hz
Serial #: DC32363EBENG
Model: DELL 1907FP

Manufacturer ID/Model: DEL4026
Resolution: 1280x1024 @ 75 Hz
Serial #: FP1827AFRFN7
Model: DELL 1908FP
```
I think that this corresponds to Display0 and Display1, respectively, but cannot confirm that.

I can see the Manifacturer ID/Model corresponds to the other info as part of the device ID but am still trying to see if there's other info I can correlate.

**Comment by dbwiddis** [comment]
After a lot of reading and a little beer, I'm circling back to the initial requests:
> First, Oshi would be solving an age old problem for Java developers who need to reliably know what monitor they are dealing with.  Finally they can use that basic Display0, Display1, Display2 and so on that Java returns to them.

This is the harder nut to crack.  Using the `java.awt` classes we can find the current monitor being used, or list all monitors (and identify where it is in the list) but there appears to be no guarantee of order.  In essence, unless I can, by coincidence, be able to correlate some difference in the monitors (resolution, etc.) with other info, I don't think there's a reliable way to map one to the other.

> Second, with this feature Oshi would be a network admins all in one dream! I remember having to manually visit every computer at a company to log the amount of monitors users had as well as their manufacture and serial numbers. It would of also been nice to easily record their date of manufacture so we could prioritize hardware upgrades. If Oshi could reliably manage this task (even other software and programming languages struggle to get monitor information) it would be a complete operating system information library.

I think I've essentially solved this part of it.  With the ability to enumerate all the connected monitors and retrieve/parse EDID, I can get/parse manufacturer, model, serial number, week and year of manufacturer, physical size, resolution, refresh rate, etc.  I can return the more common things and provide the EDID to the user should they wish to parse more. The EDID is also much more standardized and easier to get cross-platform.  From the perspective of being an information library, I think I can head down this route with oshi.

**Comment by blizzardengle** [comment]
I agree I think what you've accomplished fits perfectly with Oshi. I really look forward to using it.

<hr>

I don't think you'll use this for Oshi but I have had one radical idea that I think you would appreciate and might enjoy trying. Since Java returns that Display0, Display1...and so on, you can at least reach out to active monitors. So what about this out of the box hack.

1) Using Java, screenshot each display and toss the screenshot on each screen. Effectivly hiding what your about to do.

2) Call up a console window (with Java or another programming language) on each monitor that can query its own information. So the console runs a script that detects and returns information only for the monitor its running from.

3) In Java copy this console output one by one following what the java.awt returns as the order of monitors. Now we know which monitor corresponds to what the java.awt has.

4) Close all console windows and erase the screenshots off the screen. 

I was planning on attempting this in the future but don't have time right now. Figured I share this with you and anyone crazy enough to give it a shot.

**Comment by blizzardengle** [comment]
Oh do you want me to mark this closed or will you?

**Comment by dbwiddis** [comment]
I'll close it once I've committed the code for all 3 platforms. Give me a while (probably a week)  :)

**Comment by dbwiddis** [comment]
Committed as #108.  Check out the snapshot build if you like.

**Comment by bjxingch** [comment]
Hi I am Come form China, Not good at English
I want get the Monitor ID Like this Image 
![4](https://cloud.githubusercontent.com/assets/6262945/18742158/57237378-80e5-11e6-924d-40153dc19128.png)
I need Get the 1 Monitor origin  And 2 Monitor  origin 
Thank you

**Comment by dbwiddis** [comment]
Hi, @bjxingch .  I suggest you follow some of the links posted in the top of this thread regarding getting the Monitor ID.

OSHI can tell you how many monitors you have, and return the EDID information (which includes the resolution, manufacturer, and other statistics) but I have not found any way to correlate the OSHI array of displays directly with the Windows ID numbers.

**Comment by dbwiddis** [comment]
@bjxingch ... the accepted answer at [this StackOverflow post](http://stackoverflow.com/questions/10237937/looking-for-a-reliable-mapping-of-forms-screen-devicename-to-monitor-edid-info) shows how you can correlate the Monitor ID to the EDID, on Windows only.

I did not pursue this correlation for OSHI because it was not cross-platform, but hopefully it is helpful to you.

**Comment by bjxingch** [comment]
@dbwiddis Thank you Very much for your help .
I can't understande the Win32 class.
I will Study it.

**Comment by systemsplanet** [comment]
fyi,
https://stackoverflow.com/questions/10237937/looking-for-a-reliable-mapping-of-forms-screen-devicename-to-monitor-edid-info

Found the "missing link". The DIDD path will match the results of an EnumDisplayDevices() lookup, if you specify EDD_GET_DEVICE_INTERFACE_NAME for dwFlags! Thanks for help, Hans (feel free to post an answer if you want the bounty) – holtavolt Apr 24 '12 at 17:45

**Comment by adineag** [comment]
@dbwiddis Is there a way to correlate the GraphicsDevice.getIDstring() with the EDID info that we get from oshi in java? I don't understand the C# code in the stackoverflow link above
