### ISSUE TITLE
oren - wrapper for oshi

### ISSUE THREAD

**Issue by zcaudate** [dblock/oshi#112]
Hey! great project. I've written a clojure wrapper for the library:

https://github.com/zcaudate/oren
http://z.caudate.me/oren-os-and-hardware-information/

Thanks for all your hard work!

**Comment by dbwiddis** [comment]
Wow, thanks!  I suppose I should link to your project from the README...

**Comment by dbwiddis** [comment]
I've added a link on the README to your project! Thanks!

**Comment by zcaudate** [comment]
thanks!
