### ISSUE TITLE
Memory doesn't update

### ISSUE THREAD

**Issue by Amjad121092** [dblock/oshi#113]
Hi,

The method:

systemInfo.getHardware().getMemory().getAvailable()

doesn't update the RAM usage it always stays the same on windows unsure about other platforms.

Regards

**Comment by dbwiddis** [comment]
Wow.... it's been this way for years!  Surprised nobody noticed until now.  This is limited to the Windows port.

I'll get this fixed promptly.  In the meantime, as a workaround, you can instantiate a new instance of WindowsGlobalMemory.

**Comment by dbwiddis** [comment]
This is fixed in the current 2.2-SNAPSHOT if you'd like to test it.  I'll probably cut a 2.1.1 release this weekend.

**Comment by Amjad121092** [comment]
Thank you very much any chance you can put 2.2 on maven?

**Comment by dbwiddis** [comment]
It'll be 2.1.1, actually, and I'll release it tonight.

**Comment by dbwiddis** [comment]
2.1.1 has been released and should update in the search within about 2 hours
