### ISSUE TITLE
XML and/or JSON output

### ISSUE THREAD

**Issue by hazendaz** [dblock/oshi#115]
We are looking more at using this with psi probe sometime in the near future.  We officially made the jump to jave 7 a week or so ago.  Now we can explore this a bit. There was a request on our project in regards to oshi possibly providing xml or json output.  The Jackson libraries probably could do the trick.  For now, just wanted to put this out here.  I haven't looked to see exactly what is under the hood here but if I recall just outputs information to the terminal.  I probably can get to this at some point but would like some feedback if this seems like a good idea.

**Comment by dbwiddis** [comment]
Happy to support either or both.  Probably not too difficult.  

Take a look at [oren](https://github.com/zcaudate/oren) seems to already parse it into JSON.

**Comment by dbwiddis** [comment]
Did some looking into this.  While there are libraries (Jackson, etc.) they are all probably overkill for our needs, as we're not trying to arbitrarily parse a lot of things... we have a set list of features and we can just output them appropriately (possibly with some recursive toJSON() or toXML() calls on various classes).

I'd probably jump into doing this right now but am curious if the oren project already meets your needs.

**Comment by hazendaz** [comment]
We probably wouldn't introduce oren to psi probe as it isn't java.


Sent from Outlook Mobile






On Thu, Feb 18, 2016 at 11:52 PM -0800, "dbwiddis" <notifications@github.com> wrote:





Did some looking into this.  While there are libraries (Jackson, etc.) they are all probably overkill for our needs, as we're not trying to arbitrarily parse a lot of things... we have a set list of features and we can just output them appropriately (possibly with some recursive toJSON() or toXML() calls on various classes).

I'd probably jump into doing this right now but am curious if the oren project already meets your needs.

---

**Comment by hazendaz** [comment]
I'll wire this as is into psi probe this weekend.  I may not need xml or json just yet.  I'll get back with you.


Sent from Outlook Mobile






On Thu, Feb 18, 2016 at 11:52 PM -0800, "dbwiddis" <notifications@github.com> wrote:





Did some looking into this.  While there are libraries (Jackson, etc.) they are all probably overkill for our needs, as we're not trying to arbitrarily parse a lot of things... we have a set list of features and we can just output them appropriately (possibly with some recursive toJSON() or toXML() calls on various classes).

I'd probably jump into doing this right now but am curious if the oren project already meets your needs.

---

**Comment by dbwiddis** [comment]
but I think JSON is a great idea and extremely simple to implement, so I'll probably do that anyway. 

add toJSON() methods to all the implementing classes, producing unformatted JSON.   Implement toString() pretty-printing the JSON.

**Comment by dbwiddis** [comment]
Current output:
```
{
  "operatingSystem": {
    "manufacturer": "Apple",
    "family": "Mac OS X",
    "version": {
      "version": "10.11.3",
      "codeName": "El Capitan",
      "build": "15D21"
    }
  },
  "hardware": "null"
}
```

**Comment by dbwiddis** [comment]
Annnnd.... done.
```
{
  "operatingSystem": {
    "manufacturer": "Apple",
    "family": "Mac OS X",
    "version": {
      "version": "10.11.3",
      "codeName": "El Capitan",
      "build": "15D21"
    }
  },
  "hardware": {
    "processor": {
      "name": "Intel(R) Core(TM) i7-2820QM CPU @ 2.30GHz",
      "physicalProcessorCount": 4,
      "logicalProcessorCount": 8,
      "systemSerialNumber": "C02FG4YXDF91",
      "vendor": "GenuineIntel",
      "vendorFreq": 2300000000,
      "cpu64bit": true,
      "family": "6",
      "model": "42",
      "stepping": "7",
      "systemCpuLoadBetweenTicks": 0.10365506873092176,
      "systemCpuLoadTicks": [
        9549271,
        0,
        12013691,
        186462830
      ],
      "systemCpuLoad": 0.2676056338028169,
      "systemLoadAverage": 2.51171875,
      "processorCpuLoadBetweenTicks": [
        0.28124867204216947,
        0.014036510216997632,
        0.17113028602492894,
        0.014894135861115793,
        0.1608124419518269,
        0.015012852078477919,
        0.15699679427756297,
        0.015108301916991944
      ],
      "processorCpuLoadTicks": [
        [
          2529326,
          0,
          4784074,
          18689900
        ],
<snip>
        [
          177862,
          0,
          215003,
          25610348
        ]
      ],
      "systemUptime": 260024
    },
    "memory": {
      "available": 4013109248,
      "total": 17179869184
    },
    "powerSources": [
      {
        "name": "InternalBattery-0",
        "remainingCapacity": 1.0,
        "timeRemaining": -2.0
      }
    ],
    "fileStores": [
      {
        "name": "C",
        "description": "Network Drive",
        "usableSpace": 40554176512,
        "totalSpace": 68717375488
      },
      {
        "name": "Macintosh HD (/)",
        "description": "Volume",
        "usableSpace": 1269429940224,
        "totalSpace": 1999539175424
      },
      {
        "name": "Time Machine Backups",
        "description": "Volume",
        "usableSpace": 5163308646400,
        "totalSpace": 5828831100928
      }
    ],
    "displays": [
      {
        "edid": "00FFFFFFFFFFFF0006102792250C2C162C160104B53C2278226FB1A7554C9E250C505400000001010101010101010101010101010101565E00A0A0A029503020350055502100001A1A1D008051D01C204080350055502100001C000000FF004330324A4D325046463247430A000000FC005468756E646572626F6C740A2001C702030CC12309070783010000565E00A0A0A029503020350055502100001A1A1D008051D01C204080350055502100001C0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000013"
      }
    ]
  }
}
```

**Comment by dbwiddis** [comment]
2.2-SNAPSHOT has the toJSON() methods on a lot of stuff. Try it out!

**Comment by hazendaz** [comment]
Nice work!


Sent from Outlook Mobile






On Fri, Feb 19, 2016 at 3:16 PM -0800, "dbwiddis" <notifications@github.com> wrote:





Annnnd.... done.
```
{
  "operatingSystem": {
    "manufacturer": "Apple",
    "family": "Mac OS X",
    "version": {
      "version": "10.11.3",
      "codeName": "El Capitan",
      "build": "15D21"
    }
  },
  "hardware": {
    "processor": {
      "name": "Intel(R) Core(TM) i7-2820QM CPU @ 2.30GHz",
      "physicalProcessorCount": 4,
      "logicalProcessorCount": 8,
      "systemSerialNumber": "C02FG4YXDF91",
      "vendor": "GenuineIntel",
      "vendorFreq": 2300000000,
      "cpu64bit": true,
      "family": "6",
      "model": "42",
      "stepping": "7",
      "systemCpuLoadBetweenTicks": 0.10365506873092176,
      "systemCpuLoadTicks": [
        9549271,
        0,
        12013691,
        186462830
      ],
      "systemCpuLoad": 0.2676056338028169,
      "systemLoadAverage": 2.51171875,
      "processorCpuLoadBetweenTicks": [
        0.28124867204216947,
        0.014036510216997632,
        0.17113028602492894,
        0.014894135861115793,
        0.1608124419518269,
        0.015012852078477919,
        0.15699679427756297,
        0.015108301916991944
      ],
      "processorCpuLoadTicks": [
        [
          2529326,
          0,
          4784074,
          18689900
        ],
<snip>
        [
          177862,
          0,
          215003,
          25610348
        ]
      ],
      "systemUptime": 260024
    },
    "memory": {
      "available": 4013109248,
      "total": 17179869184
    },
    "powerSources": [
      {
        "name": "InternalBattery-0",
        "remainingCapacity": 1.0,
        "timeRemaining": -2.0
      }
    ],
    "fileStores": [
      {
        "name": "C",
        "description": "Network Drive",
        "usableSpace": 40554176512,
        "totalSpace": 68717375488
      },
      {
        "name": "Macintosh HD (/)",
        "description": "Volume",
        "usableSpace": 1269429940224,
        "totalSpace": 1999539175424
      },
      {
        "name": "Time Machine Backups",
        "description": "Volume",
        "usableSpace": 5163308646400,
        "totalSpace": 5828831100928
      }
    ],
    "displays": [
      {
        "edid": "00FFFFFFFFFFFF0006102792250C2C162C160104B53C2278226FB1A7554C9E250C505400000001010101010101010101010101010101565E00A0A0A029503020350055502100001A1A1D008051D01C204080350055502100001C000000FF004330324A4D325046463247430A000000FC005468756E646572626F6C740A2001C702030CC12309070783010000565E00A0A0A029503020350055502100001A1A1D008051D01C204080350055502100001C0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000013"
      }
    ]
  }
}
```


---

**Comment by hazendaz** [comment]
I was able to utilize the current OSHI test case to produce this output in psi-probe (copy/paste with modifications).  When I tried to call the JSON piece in the current test, it fails.  I'll have to circle back to that as ultimately we will provide an entire REST api and this will be a part of it.  For now, this is the quick solution and it works quite well on my early tests using our current JSP view.

![oshi](https://cloud.githubusercontent.com/assets/975267/13207233/404c69ce-d8da-11e5-9d8d-614fe841c708.png)

**Comment by dbwiddis** [comment]
I suspect it's a special character escaping issue. File paths have / or \. Can you try a toJSON() on a class that doesn't include those?

**Comment by dbwiddis** [comment]
PR #117 properly escapes the JSON.  Can you take a look at 2.2-SNAPSHOT and see if it fixes your errors?

If you go with your existing parsing I'd suggest nixing the tick count and its associated 1-second delay.  Also note the file system call may incur some delay depending on speed of hard drives and/or network delays with shared drives.

**Comment by hazendaz** [comment]
I'll take a look at this tonight.  Thanks.


Sent from Outlook Mobile






On Sun, Feb 21, 2016 at 11:32 PM -0800, "dbwiddis" <notifications@github.com> wrote:





PR #117 properly escapes the JSON.  Can you take a look at 2.2-SNAPSHOT and see if it fixes your errors?

If you go with your existing parsing I'd suggest nixing the tick count and its associated 1-second delay.  Also note the file system call may incur some delay depending on speed of hard drives and/or network delays with shared drives.

---

**Comment by dbwiddis** [comment]
With a little prompting from @dblock I switched the JSON code to use `javax.json` which handles the string escaping, pretty printing, and all the other stuff internally.  Code looks (and smells) much cleaner now.  2.2-SNAPSHOT updated with the latest.

**Comment by akoshpinter** [comment]
Hello,

there is a bug in case of Windows OS and toJSON()

```
java.lang.UnsupportedOperationException
	at oshi.hardware.platform.windows.WindowsCentralProcessor.isCpu64bit(WindowsCentralProcessor.java:350)
	at oshi.hardware.platform.windows.WindowsCentralProcessor.toJSON(WindowsCentralProcessor.java:666)
```

**Comment by dbwiddis** [comment]
Are you using the 2.1.1 version?  The toJSON() method was totally rewritten in the current snapshot.

**Comment by dbwiddis** [comment]
Ah, nevermind.  I see that most of those processor methods aren't implemented on Windows.  I'll fix that.

**Comment by dbwiddis** [comment]
No reason for unsupported operation on those when we can parse the Identifier string.  I've updated the code and will be releasing 2.1.2 momentarily.  Look for it in a few hours.

**Comment by akoshpinter** [comment]
Great, thanks!

**Comment by dbwiddis** [comment]
Closing this as 2.1.2 has properly parsed JSON.  @hazendaz  let me know if you need anything else for output!
