### ISSUE TITLE
Is it possible to read I/O wait information?

### ISSUE THREAD

**Issue by akoshpinter** [dblock/oshi#126]
Hello,

Would it be possible to read iowait information as CPU ticks?

**Comment by dbwiddis** [comment]
Yes and no....

On Linux, apparently `/proc/stat` (which we currently parse for user/nice/system/idle) contains the info which we could stick in another variable to report.  _(Note: while researching this I see a bug in which we only count 'idle' ticks but should sum all the columns after idle which include iowait.)_

On Windows there are PerfMon counters that may apply but they are average, not cumulative like the Linux version.  You can measure [Avg. Disk sec/Transfer](https://blogs.technet.microsoft.com/askcore/2012/02/07/measuring-disk-latency-with-windows-performance-monitor-perfmon/) and you can then also read Avg. Disk Transfers/sec, and multiply sec/Transfer * transfers/sec * seconds between reads to get a total to accumulate on a counter similar to how we accumulate usage ticks.

If we implemented iowait we should probably also add on the next `/proc/stat` column for hardware irq interrupts.  (There's a Windows PerfMon for Processor% Interrupt Time).   There's no Windows equivalent for the Linux softirq.)

Unfortunately, this information is not tracked at all in OS X.  There are utilities to monitor disk and irq access times in real time (`latency` command, `dtrace` with various scripts) but these require admin permission and are well outside the scope of anything we'd want in Oshi.  We'd probably just report 0 for these counters.

I'm holding off on doing anything yet while I think about whether we want these as part of the processor, or perhaps a separate class with expanded disk i/o stats (and maybe network io stats)...

**Comment by dbwiddis** [comment]
Finally getting around to this.  I'll be adding methods to the `CentralProcessor` classes to return iowait and irq ticks.  As noted above, these will return 0 for OS X.

**Comment by dbwiddis** [comment]
Fixed/Implemented in #137
