### ISSUE TITLE
Oshi breaks on some Xeon processors

### ISSUE THREAD

**Issue by phoenixjiangnan** [dblock/oshi#127]
Nowadays, we have more and more processors with [hyper-threading technology](https://en.wikipedia.org/wiki/Hyper-threading), which may break oshi's rule with exceptions thrown like 'java.lang.IllegalArgumentException: Processor number (16) must be less than the number of CPUs: 16'. We just ran into problems when running oshi on top of this kind of processors on Windows.

Can you please confirm if Oshi is already compatible with those processors? If not, we'd better open a bug for it. Thanks!

**Comment by dbwiddis** [comment]
Oshi is compatible with hyperthreading.  On my machine I have 4 cores but 8 logical CPUs and it handles it just fine.

It does have some limitations in total number of processors based on the JNA implementation it uses.  For example, the [GetLogicalProcessorInformation](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683194(v=vs.85).aspxl) function only works up to 64 logical processors (hyperthreading on a 32-core machine).  This limitation could be worked around if necessary, but nobody has asked for that capability yet.

Of note, the error you quote about "processor number" was only applicable to the Processor implementation in version 1.x.  It should no longer be present in version 2.x.  It is possible there was a another bug in the prior implementation and I'd be happy to look further into it, but I'd suggest using a more recent version first to see if it solves the issue.

**Comment by phoenixjiangnan** [comment]
Thanks for the message! Yes, we are using 1.x version, because 2.x also requires upgrading jna, which we didn't want to do at that time. Oshi 1.x seems work fine with most hyper-threading processors but a few exceptional ones like, as far as I know, some intel xeon processors.

We will consider to upgrade to 2.x if necessary. Thanks very much for the awesome work on Oshi!

**Comment by dbwiddis** [comment]
Was the error using the code in the SystemInfoTest class (processor #s are 0-indexed)?

Looking at the 1.x code, it looks like it counts total processors using the system registry, but then has the logical processor limit based on the GetLogicalProcessorInformation function referenced above.  I'd need a closer look at the registry entries on the problematic system to figure out what was going on.  

Another difference could be if you're running oshi as a 32-bit application on a 64-bit system.

**Comment by dbwiddis** [comment]
Another possible difference may be in the treatment of NUMA nodes.  If this is the unique factor of the machines that are breaking, I can probably figure out how to fix it.
