### ISSUE TITLE
LinuxDisplay.getDisplays() throws NullPointerException

### ISSUE THREAD

**Issue by svilenvul** [dblock/oshi#134]
I am currently working on Eclipse OSGi Plug-in, that is using oshi to provide system information.

I made a test plug-in, that is executed in Jenkins on Linux platform. The build fails, because
a  NullPointerException is thrown 

`Caused by: java.lang.NullPointerException: null
	at oshi.hardware.platform.linux.LinuxDisplay.getDisplays(LinuxDisplay.java:74) ~[na:na]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.getDisplays(LinuxHardwareAbstractionLayer.java:133) ~[na:na]`

when I try to call 

`SysteminfoInterface systeminfo = new SystemInfo();
HardwareAbstractionLayer hal = systemInfo.getHardware();
displays = hal.getDisplays();`

Locally (on my windows machine) the test is executed without any problem.

**Comment by svilenvul** [comment]
Sorry, I saw the pull request for it - https://github.com/dblock/oshi/pull/132.
I suppose it is fixed.

**Comment by dbwiddis** [comment]
Yep, fixed. I should probably get around to making a release but had a few more things being worked.  You can use the snapshot if it's critical.
