### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by henryx** [dblock/oshi#135]
Currently it seems that Oshi have only a sample output but anything that show the code used for generate it. Is it possible to add the code in the documentation?

**Comment by dbwiddis** [comment]
The sample output is generated from the `SystemInfoTest` class which is available to review.  Most of it is just outputting the values from all the various objects' methods with minor formatting.  (The Display stuff is probably a bit more, but it's hardly complete.)

Which specific pieces of the sample output need more documentation?

**Comment by dblock** [comment]
Maybe just link the code from README?

**Comment by dbwiddis** [comment]
@henryx would linking in the README file to the [SystemInfoTest](https://github.com/dblock/oshi/blob/master/src/test/java/oshi/SystemInfoTest.java) class be sufficient documentation?  Its `main()` method is what produces the sample output you see.

**Comment by henryx** [comment]
Yes, it would be a sufficient documentation

**Comment by dbwiddis** [comment]
Fixed in #137
