### ISSUE TITLE
CPU load

### ISSUE THREAD

**Issue by kamenitxan** [dblock/oshi#14]
Hi,
I tried to implement CPU load for Mac(Linux), but I have problem with ExecutingCommand.getFirstAnswer("top -l 1 | awk '/CPU usage/ {print $7}' | sed s/%//")

Command works great in terminal and I have no idea why it's not returning anything.

$ top -l 1 | awk '/CPU usage/ {print $7}' | sed s/%//
70.73

How can I fix it? Also I'm not able to implement it on Windows, hope I can still creal pull request.

**Comment by kamenitxan** [comment]
It works without pipes and with small change in ```ExecutingCommand```. It should work on linux without changes and i have found it for windows on stackowerflow. But I have not tested it on linux and win, so it throws ```UnsupportedOperationException```.

**Comment by trejkaz** [comment]
"top" can probably be done in code as well. Most of those little utilities are just reading from files in /proc...

**Comment by kamenitxan** [comment]
In Linux it's actually reading from /proc/stat.

**Comment by Sorceror** [comment]
IMHO `UnsupportedOperationException` is a quite bad choice, because it's runtime exception. I would rather return result value which will not pass test but won't kill whole app (like '-1' or something).

**Comment by dblock** [comment]
I think I politely disagree with @Sorceror, because returning the wrong result leads to all kinds of real world problems (think space shuttle :)).

**Comment by Sorceror** [comment]
Well ok, but RuntimeException is kind of hell for developers/users, especially when there is no documentation in code which tells you that.. If invalid value is not the way, then regular exception will do the work (I know you need to catch them, but then users/developers won't be surprised whenever whole app crashes due to runtime expcetion).

**Comment by dblock** [comment]
You can raise a more specialized exception of course.

**Comment by Sorceror** [comment]
Sure, but I mean that runtime expcetion in general are bad concept for whole project (in my opinion). I'll use them because codebase is using them, I just don't agree with them :).

**Comment by kamenitxan** [comment]
I think that UnsupportedOperationException is ok if feature is not implemented on some of the platforms. If it returns "-1", user could think, it's working correctly.

**Comment by dblock** [comment]
Thanks everyone, I shall make the executive decision that we want an exception when something is not working or is unsupported. No hard feelings, we have to pick something :)
