### ISSUE TITLE
Get Filesystem Type

### ISSUE THREAD

**Issue by lumacafi** [dblock/oshi#146]
Would be at all possible to get the filesystem type information. (FAT, NTFS, etx2, ext4, etc)
So each filestore object would have an attribute with this information.

**Comment by dbwiddis** [comment]
It is certainly possible.
- On windows. [GetVolumeInformation](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364993(v=vs.85).aspx) has the info.
- On Linux, [getfsfile()](http://man7.org/linux/man-pages/man3/getfsent.3.html) has a `fs_vfstype` field.
- On OS X, [getfsstat()](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man2/getfsstat.2.html) returns a `statfs` structure.

It may be a week or two before I can get to this, so you're welcome to take a shot at it first.

**Comment by dbwiddis** [comment]
Starting work on this in #150. OS X done:
```
[main] INFO oshi.SystemInfoTest - Checking File System...
File System:
 C (Network Drive) [smbfs] 37.7 GiB of 64.0 GiB free (58.9%)
 Dropbox (Volume) [hfs] 827.5 GiB of 931.0 GiB free (88.9%)
 Macintosh HD (/) (Volume) [hfs] 1.3 TiB of 1.8 TiB free (73.8%)
 MobileBackups (Network Drive) [mtmfs] 0 bytes of 1.8 TiB free (0.0%)
```

**Comment by dbwiddis** [comment]
Linux:
```
File System:
 / (Local Disk) [ext4] 51.1 GiB of 60.9 GiB free (83.8%)
 iCloud (Mount Point) [prl_fs] 1.3 TiB of 1.8 TiB free (73.9%)
 Dropbox (Mount Point) [prl_fs] 827.5 GiB of 931.0 GiB free (88.9%)
```

**Comment by dbwiddis** [comment]
And... Windows.
```
File System:
 Floppy Disk Drive (A:) (Floppy Disk Drive) [FAT] 1.1 MiB of 1.4 MiB free (82.4%)
 Local Disk (C:) (Local Disk) [NTFS] 37.7 GiB of 64.0 GiB free (58.9%)
 MobileBackups on 'Mac' (V:) (Network Drive) [PrlSF] 0 bytes of 1.8 TiB free (0.0%)
```
