### ISSUE TITLE
CPU Temerature and CPU Voltage

### ISSUE THREAD

**Issue by ashishpatel1992** [dblock/oshi#151]
CPU Temperature and CPU Voltage are showing as zero in Windows 10 Laptop.
Tested on Dell Laptop and HP Laptop.
Here is the output 
`{"cpuTemperature":0.0,"fanSpeeds":[0],"cpuVoltage":0.0}`
Any solution to it?

**Comment by ashishpatel1992** [comment]
Just for information In [CPUID  HWMonitor](http://www.cpuid.com/softwares/hwmonitor.html) Temperature and voltages are showing perfectly.

**Comment by dbwiddis** [comment]
As described in the [Javadoc for Sensors](http://dblock.github.io/oshi/apidocs/), "Windows information is retrieved via Windows Management Instrumentation (WMI). Unfortunately, most hardware providers do not publish values to WMI. If a value is not available through the Microsoft API, Oshi will attempt to retrieve values as published by the Open Hardware Monitor (http://openhardwaremonitor.org/) if it is running."

This is a shortened version of a longer discussion in #121 describing possible other "solutions", but the bottom line is that it's not easy.  I welcome others to try to do more but I've reached the limit of what I can do. :)

**Comment by dbwiddis** [comment]
I think I might wright up a FAQ answering this and a few other missing data "exceptions".

**Comment by ashishpatel1992** [comment]
Using WMI we can do it. It gives Latest Temperature sensor details
Check out My Answer at [StackOverFlow](http://stackoverflow.com/questions/21884264/retrieve-intel-pch-temperature-with-powershell/36915900#36915900)
Tested this WMI code in different computers and it works.

**Comment by dbwiddis** [comment]
OSHI attempts the following for temperature:
```
wmic /namespace:\\root\wmi PATH MSAcpi_ThermalZoneTemperature get CurrentTemperature 
wmic /namespace:\\root\wmi PATH Win32_TemperatureProbe get CurrentReading 
wmic temperature get CurrentReading
```
What additional command should be attempted?   It has to be standard commandline, not powershell.

**Comment by ashishpatel1992** [comment]
You need command 
`wmic /namespace:\\root\cimv2 PATH Win32_PerfFormattedData_Counters_ThermalZoneInformation get Temperature`
This will give you live temerature
The temperature is in Kelvin So you can convert it to F or C based on users choice.

**Comment by dbwiddis** [comment]
I've added that string as another possible option in the current 2.4-SNAPSHOT.  (It converts to C.)
