### ISSUE TITLE
List USB devices

### ISSUE THREAD

**Issue by dbwiddis** [dblock/oshi#160]
Name may be sufficient, although if there's a unique ID/path/etc. to add that would be useful.  If we can do a tree-based structure where devices are shown under the hubs they're connected to, even better.

Linux:
- Similar to output of `lsusb -t` command.
- Possible to parse `/sys/bus/usb/devices/*/product` or other info

MacOS:
- See output of `ioreg -p IOUSB -w0` and get same information via IOKit

Windows:
- Registry: HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Enum\USB.
- [GetRawInputDeviceList](https://msdn.microsoft.com/en-us/library/windows/desktop/ms645598(v=vs.85).aspx) and [GetRawInputDeviceInfo](https://msdn.microsoft.com/en-us/library/windows/desktop/ms645597(v=vs.85).aspx) functions
- Possible to use WMI with Namespace: root\CIMV2, Class Win32_SerialPort or Win32_USBHub or Win32_PnPEntity where DeviceID Like ""USB%""", Properties: PNPDeviceID, DeviceID, Description

**Comment by dbwiddis** [comment]
Take a look at [this Tree class](http://stackoverflow.com/questions/3522454/java-tree-data-structure) as a possible template for storing these things.

**Comment by dbwiddis** [comment]
OS X done...
```
[main] INFO oshi.SystemInfoTest - Checking USB Devices...
USB Devices:
 USB20Bus
   FaceTime HD Camera (Built-in) (Apple Inc.) [s/n: DJHB1V077FDH7HL0]
   hub_device
     Apple Internal Keyboard / Trackpad (Apple Inc.)
     BRCM2070 Hub (Apple Inc.)
       Bluetooth USB Host Controller (Apple Inc.)
 USB20Bus
   hub_device
     USB Receiver (Logitech)
     IR Receiver (Apple Computer, Inc.)
 USB20Bus
   hub_device
     USB2.0 Hub
       Fitbit Base Station (Fitbit Inc.)
       ANT USBStick2 (Dynastream Innovations) [s/n: 051]
       Fitbit Base Station (Fitbit Inc.)
     FaceTime HD Camera (Display) (Apple Inc.) [s/n: CCGCAN000TDJ9DFX]
     Apple Thunderbolt Display (Apple Inc.) [s/n: 162C0C25]
     Display Audio (Apple Inc.) [s/n: 162C0C25]
```

**Comment by dbwiddis** [comment]
Linux done, needs testing by someone with a real Linux machine for devices not directly attached to a hub...
```
[main] INFO oshi.SystemInfoTest - Checking USB Devices...
USB Devices:
 EHCI Host Controller (Linux 3.16.0-71-generic ehci_hcd) [s/n: 0000:00:1d.7]
   FaceTime HD Camera (Display) (Parallels) [s/n: 0x4015000005ac1112]
   FaceTime HD Camera (Built-in) (Parallels) [s/n: 0xfa20000005ac8509]
 UHCI Host Controller (Linux 3.16.0-71-generic uhci_hcd) [s/n: 0000:00:1d.0]
 xHCI Host Controller (Linux 3.16.0-71-generic xhci_hcd) [s/n: 0000:00:1d.6]
 xHCI Host Controller (Linux 3.16.0-71-generic xhci_hcd) [s/n: 0000:00:1d.6]
```

**Comment by dbwiddis** [comment]
Annnnd, the Windows code is in.   Committed as #181 .   Would appreciate @henryx testing linux if you have some time.

**Comment by dbwiddis** [comment]
Thanks!  As you can see from the example, it gets the buses/controllers and devices directly under them, but I haven't been able to test daisy-chained devices (attached to a hub, etc.) because my VM doesn't present them that way.  Should correspond to files `/sys/bus/usb/devices/1-1.1` or similar... something with at least one period!

**Comment by henryx** [comment]
Ok, I've tested with a chain of devices (an USB hub with attached two USB
keys) and it reports only second level of the USB chain. This is the output
(the USB device ALCOR is the USB hub):

USB Devices:
 EHCI Host Controller (Linux 4.5.5-201.fc23.x86_64 ehci_hcd) [s/n:
0000:00:1a.7]
 EHCI Host Controller (Linux 4.5.5-201.fc23.x86_64 ehci_hcd) [s/n:
0000:00:1d.7]
 |-- DT Micro (Kingston) [s/n: 50E549C20289FD112991276F]
 UHCI Host Controller (Linux 4.5.5-201.fc23.x86_64 uhci_hcd) [s/n:
0000:00:1a.0]
 |-- USB Receiver (Logitech)
 UHCI Host Controller (Linux 4.5.5-201.fc23.x86_64 uhci_hcd) [s/n:
0000:00:1a.1]
 UHCI Host Controller (Linux 4.5.5-201.fc23.x86_64 uhci_hcd) [s/n:
0000:00:1a.2]
 UHCI Host Controller (Linux 4.5.5-201.fc23.x86_64 uhci_hcd) [s/n:
0000:00:1d.0]
 |-- USB Hub 2.0 (ALCOR)
 UHCI Host Controller (Linux 4.5.5-201.fc23.x86_64 uhci_hcd) [s/n:
0000:00:1d.1]
 UHCI Host Controller (Linux 4.5.5-201.fc23.x86_64 uhci_hcd) [s/n:
0000:00:1d.2]
 |-- USB Receiver (Logitech)
 |-- USB Receiver (Logitech)

If you want, I'll investigate why it doesn't work


2016-06-03 10:12 GMT+02:00 dbwiddis <notifications@github.com>:

**Comment by dbwiddis** [comment]
First, confirm it's not working.  It's possible that Linux is listing all of your devices at the second level.  If you list the contents of `/sys/bus/usb/devices` are there any links there of the form #-#.# ?   If so, the code is broken.  If not, it's behaving exactly as designed.

The code first looks for the controllers:
* File `usb1`, `usb2`, etc.

Then the next level devices/hubs: 
* Devices `1-1` and `1-2` are under `usb1`, `2-1`  and `2-2` under `usb2`, etc.

Then any devices under that:
* Devices `1-1.1` and `1-1.2` are under `1-1`, etc.

Ignore any devices with a colon, e.g., `1-0:1.0`. These are bus interfaces.

My VM does not have any devices below that first level (I have 4-1 and 4-2) so I can't test 4-1.1, etc.

If there is a bug it's probably with `LinuxUsbDevice.java` line 91:
```
final Pattern p = Pattern.compile(parent.length() > 0 ? parent + "\\.\\d+" : "\\d+-\\d+");
```
When called based on only the bus, it looks in the directory `/sys/bus/usb/devices/usb1` where it will find `1-1`, `1-2`, etc.  When called with a parent, e.g., `1-1` it's supposed to append a period and a number (e.g., `1-1.1`).  I think it's right, but I may not have the escapes correct.

**Comment by dbwiddis** [comment]
Hmm... might be a hyphen (`1-1-1` rather than `1-1.1`).

I based the period version from [this site](http://www.linux-usb.org/FAQ.html#i6), which says the format is `bus-port.port.port`. But [this other site](http://www.makelinux.net/ldd3/chp-13-sect-2) claims the format is `root_hub-hub_port-hub_port`

**Comment by henryx** [comment]
Mmm... Based of the response of my Linux workstation (kernel 4.5.5, but I
think is the same on old kernels), when I attach the USB hub, I have this
result:

/sys/bus/usb/devices/6-0:1.0 # the bus
/sys/bus/usb/devices/6-2 # the hub USB
/sys/bus/usb/devices/6-2.1 # one USB key attached to the hub
/sys/bus/usb/devices/6-2.3 # one USB key attached to the hub

So, one method for showing attached devices to the USB hub might be iterate
all directories which name starts with a number and the name does not
contain a colon...
Another two things before start to fix it: first, with the USB hub
attached, the number of the /sys/bus/usb/devices/usb* directories is the
same. Second, I want to view what if is the result if I attach an USB hub
to the USB hub (it seems an Inception-scenario ;) )


2016-06-07 3:04 GMT+02:00 dbwiddis <notifications@github.com>:

**Comment by dbwiddis** [comment]
OK, so it looks like it SHOULD be as I've designed it, but if those USB keys are not showing up in the output then the parsing of the 6-2.1 and 6-2.3 parts are broken.  (I believe my iteration ignores the colon.)

I had looked in `/sys/bus/usb/devices/usb6` to find those values, and it may be the nested directory structure doesn't work at that level (may be /usb6/6-2/6-2.1 perhaps?) and I need to look in the higher level directory and match the 6- portion...

See what you can find with debugging!

**Comment by dbwiddis** [comment]
OK, I think I've identified the problem.

While all the files are present at the same level in `/sys/bus/usb/devices` I started drilling down the directory structure using the usb buses.  However, once you go into a directory structure you have to nest directories.

So I need to either have it stay in the `/sys/bus/usb/devices` folder and look only at the filenames or navigate down the directory tree looking for the other devices (modify my recursive calls using path).  I'll post here in a bit with suggested changes.

**Comment by dbwiddis** [comment]
Here's a diff file showing changes that I think should work...
```
Index: src/main/java/oshi/hardware/platform/linux/LinuxUsbDevice.java
===================================================================
@@ -69,8 +69,11 @@
 
         List<UsbDevice> usbDevices = new ArrayList<UsbDevice>();
         for (File bus : buses) {
+            // These will have filename usb1, usb2, etc.
+            String prefix = bus.getName().replace("usb", "") + "-";
             // bus.toString() is path to info files and any nested devices
-            usbDevices.add(getUsbDevice(bus.toString() + "/", ""));
+            usbDevices.add(getUsbDevice(bus.toString(), prefix));
         }
         return usbDevices.toArray(new UsbDevice[usbDevices.size()]);
     }
@@ -80,15 +83,17 @@
      * 
      * @param path
      *            Path to the device
+     * @param prefix
+     *            Device prefix to restrict recursive searches
      * @return The corresponding USB device
      */
-    private static UsbDevice getUsbDevice(String path, String parent) {
-        String name = FileUtil.getStringFromFile(path + parent + "/product");
-        String vendor = FileUtil.getStringFromFile(path + parent + "/manufacturer");
-        String serialNumber = FileUtil.getStringFromFile(path + parent + "/serial");
+    private static UsbDevice getUsbDevice(String path, String prefix) {
+        String name = FileUtil.getStringFromFile(path + "/product");
+        String vendor = FileUtil.getStringFromFile(path + "/manufacturer");
+        String serialNumber = FileUtil.getStringFromFile(path + "/serial");
 
-        File usbdir = new File(path);
-        final Pattern p = Pattern.compile(parent.length() > 0 ? parent + "\\.\\d+" : "\\d+-\\d+");
+        File usbdir = new File(USB_ROOT);
+        final Pattern p = Pattern.compile(prefix + "\\d+");
         File[] devices = usbdir.listFiles(new FileFilter() {
             @Override
             public boolean accept(File file) {
@@ -97,21 +102,23 @@
         });
 
         return new LinuxUsbDevice(name, vendor, serialNumber,
-                devices == null ? new UsbDevice[0] : getUsbDevices(path, devices));
+                devices == null ? new UsbDevice[0] : getUsbDevices(prefix, devices));
     }
 
     /**
      * Get all USB devices at the specified paths
      * 
+     * @param prefix
+     *            Device prefix to restrict recursive searches
      * @param devices
      *            an array of File objects with paths to devices
      * @return an array of corresponding USB devices
      */
-    private static UsbDevice[] getUsbDevices(String path, File[] devices) {
+    private static UsbDevice[] getUsbDevices(String prefix, File[] devices) {
         List<UsbDevice> usbDevices = new ArrayList<UsbDevice>();
         for (File device : devices) {
             // device.toString() is path to info files and any nested devices
-            usbDevices.add(getUsbDevice(path, device.toString().replace(path, "")));
+            usbDevices.add(getUsbDevice(device.getPath(), device.getName() + "."));
         }
         return usbDevices.toArray(new UsbDevice[usbDevices.size()]);
     }
```

**Comment by dbwiddis** [comment]
As an alternative to parsing sysfs, you might consider a complete rewrite using this as a start:
```
  enumerate = udev_enumerate_new(udev);
  udev_enumerate_add_match_subsystem(enumerate, "usb");
  udev_enumerate_scan_devices(enumerate);
  devices = udev_enumerate_get_list_entry(enumerate);
```

**Comment by dbwiddis** [comment]
OK... ignore what you have.  I've figured out how to get it from udev per the previous comment.
```
    public static UsbDevice[] getUsbDevices() {
        // See http://www.signal11.us/oss/udev/
        // Create the udev object
        Udev.UdevHandle udev = Udev.INSTANCE.udev_new();
        // Create a list of the devices in the 'usb' subsystem.
        UdevEnumerate enumerate = Udev.INSTANCE.udev_enumerate_new(udev);
        Udev.INSTANCE.udev_enumerate_add_match_subsystem(enumerate, "usb");
        Udev.INSTANCE.udev_enumerate_scan_devices(enumerate);
        UdevListEntry devices = Udev.INSTANCE.udev_enumerate_get_list_entry(enumerate);

        // For each item enumerated, print out its information.
        for (UdevListEntry dev_list_entry = devices; dev_list_entry != null; dev_list_entry = Udev.INSTANCE
                .udev_list_entry_get_next(dev_list_entry)) {

            // Get the filename of the /sys entry for the device and create a
            // udev_device object (dev) representing it
            String path = Udev.INSTANCE.udev_list_entry_get_name(dev_list_entry);
            UdevDevice dev = Udev.INSTANCE.udev_device_new_from_syspath(udev, path);
            // If we don't have a bDeviceClass, this is an interface; ignore
            if (Udev.INSTANCE.udev_device_get_sysattr_value(dev, "bDeviceClass") == null) {
                continue;
            }

            // The device pointed to by dev contains information about the usb
            // device. From here, we can call get_sysattr_value() for each file
            // in the device's /sys entry. The strings passed into these
            // functions (idProduct, idVendor, serial, etc.) correspond directly
            // to the files in the directory which represents the USB device.
            // Note that USB strings are Unicode, UCS2 encoded, but the strings
            // returned from udev_device_get_sysattr_value() are UTF-8 encoded.
            System.out.format("  %s (%s) [s/n: %s]\n", Udev.INSTANCE.udev_device_get_sysattr_value(dev, "product"),
                    Udev.INSTANCE.udev_device_get_sysattr_value(dev, "manufacturer"),
                    Udev.INSTANCE.udev_device_get_sysattr_value(dev, "serial"));
            UdevDevice parent = Udev.INSTANCE.udev_device_get_parent_with_subsystem_devtype(dev, "usb", "usb_device");
            if (parent != null) {
                System.out.println("  -- Parent = " + Udev.INSTANCE.udev_device_get_sysattr_value(parent, "product"));
            }
            Udev.INSTANCE.udev_device_unref(dev);
        }
        // Free the enumerator object
        Udev.INSTANCE.udev_enumerate_unref(enumerate);

        Udev.INSTANCE.udev_unref(udev);

        // TODO actually build the tree here
        return new UsbDevice[0];
    }
```
Output:
```
USB Devices:
  UHCI Host Controller (Linux 3.16.0-71-generic uhci_hcd) [s/n: 0000:00:1d.0]
  xHCI Host Controller (Linux 3.16.0-71-generic xhci_hcd) [s/n: 0000:00:1d.6]
  xHCI Host Controller (Linux 3.16.0-71-generic xhci_hcd) [s/n: 0000:00:1d.6]
  EHCI Host Controller (Linux 3.16.0-71-generic ehci_hcd) [s/n: 0000:00:1d.7]
  FaceTime HD Camera (Display) (Parallels) [s/n: 0x4015000005ac1112]
  -- Parent = EHCI Host Controller
  FaceTime HD Camera (Built-in) (Parallels) [s/n: 0xfa20000005ac8509]
  -- Parent = EHCI Host Controller
```
I'll just build the tree and it's done....

**Comment by dbwiddis** [comment]
OK, new udev-based code is in!  No more sysfs parsing.  Can you update and test?

**Comment by henryx** [comment]
I'm impressed, tomorrow I'll check this code with a multi device (USB hub,
card reader and hard disk reader, when I attach it at the PC, I view 4
disks), sadly, now I'm not able to try it

2016-06-08 20:31 GMT+02:00 dbwiddis <notifications@github.com>:

**Comment by dbwiddis** [comment]
And I've just redone the OS X version to use IOKit registry  Woohoo!

**Comment by henryx** [comment]
Ok, this is the output of USB devices:

USB Devices:
 xHCI Host Controller (Linux 4.4.9-300.fc23.x86_64 xhci-hcd) [s/n:
0000:00:14.0]
 |--
 |-- Integrated_Webcam_HD (CN0Y2TKG724873CED2F4A00) [s/n: 200901010001]
 |-- Synaptics Large Touch Screen (SYNAPTICS)
 |-- USB2.0 Hub
     |-- DataTraveler G3 (Kingston) [s/n: 001CC0EC30C4BB8125F6001A]
     |-- USB Storage [s/n: 000000009744]
     |-- USB to ATA/ATAPI bridge (JMicron) [s/n: DA22381132FF]
 xHCI Host Controller (Linux 4.4.9-300.fc23.x86_64 xhci-hcd) [s/n:
0000:00:14.0]
 EHCI Host Controller (Linux 4.4.9-300.fc23.x86_64 ehci_hcd) [s/n:
0000:00:1d.0]
 |--

It seems it works


2016-06-09 1:43 GMT+02:00 dbwiddis <notifications@github.com>:

**Comment by dbwiddis** [comment]
Excellent!  👍 

Well, almost.  I am seeing an empty string on the first line under the first controller (above your webcam) and also under the last one at the bottom of the list.  So it appears it's finding 2 devices (with udev) that are returning null for the `udev_device_get_sysattr_value()` calls.  Any chance you can figure out what's happening there?  I can always just test for null and `continue;` there but I'd prefer to know what's going on.

**Comment by dbwiddis** [comment]
Actually, OSHI may have this right, you just may have a device that's not in your usb database.  See [this page](http://ubuntuforums.org/showthread.php?t=2234649) for an example where that happens.  Typing `lsusb` should show the same two blanks if this is the case.

**Comment by henryx** [comment]
It seems that this is not the problem:

$ lsusb
Bus 001 Device 002: ID 8087:8000 Intel Corp.
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 006: ID 8087:07dc Intel Corp.
Bus 002 Device 005: ID 0bda:5752 Realtek Semiconductor Corp.
Bus 002 Device 003: ID 06cb:0af8 Synaptics, Inc.
Bus 002 Device 007: ID 152d:2329 JMicron Technology Corp. / JMicron USA
Technology Corp. JM20329 SATA Bridge
Bus 002 Device 004: ID 05e3:0716 Genesys Logic, Inc. USB 2.0 Multislot Card
Reader/Writer
Bus 002 Device 008: ID 0951:1643 Kingston Technology DataTraveler G3
Bus 002 Device 002: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
$

2016-06-09 21:38 GMT+02:00 dbwiddis <notifications@github.com>:

**Comment by dbwiddis** [comment]
Is that exactly the same usb device configuration you had?  I don't see the same devices (touch screen, web cam, etc.)

**Comment by henryx** [comment]
Yes, the PC is a Dell XPS 13 Developer Edition with Fedora 23, the USB
multifunction have attached an Western Digital hard disk and an USB key

2016-06-10 10:50 GMT+02:00 dbwiddis <notifications@github.com>:

**Comment by dbwiddis** [comment]
Well, can you throw in a few debug statements to see if we can figure out what's going on?  It's returning a device from the "usb" sybsystem that is of type "usb_device" but returns null for the product, manufacturer, and serial keys.   Throwing in a debug statement after this line
```
            String value = Udev.INSTANCE.udev_device_get_sysattr_value(dev, "product");
```
and reporting the path value when value == null should identify the two devices showing up blank.  You can then investigate in the sysfs tree what these devices are and why that info is blank.

**Comment by dbwiddis** [comment]
Cross-referencing your lsusb output to the other list I think I've ID'd the devices.  Since most of your devices are on bus 2, I know the controller with no devices is bus 3 (your USB 3.0 root hub) and the one with a single device is bus 1, which has only one other device:
```
Bus 001 Device 002: ID 8087:8000 Intel Corp.
```
This is apparently an [Integrated Rate Matching Hub/Generic USB Hub](https://usb-ids.gowdy.us/read/UD/8087/8000)
I can guess that the other blank device is 
```
Bus 002 Device 006: ID 8087:07dc Intel Corp.
```
This is apparently [a Bluetooth 4.0 controller](https://usb-ids.gowdy.us/read/UD/8087/07dc).

Neither of these product ids are in the [usb.ids](http://www.linux-usb.org/usb.ids) file (in theory you could manually add them).

So lsusb is apparently looking up the vendor ID of 8087 and publishing that (hence the "Intel Corp.", but can't seem to match the product ID's of 8000 and 07dc which are probably blank in sysfs.  (You can confirm by looking for the 1-2 and 2-6 devices.)

So... nothing wrong with the code, apparently. This is a real device that simply doesn't have a name in the database.   In #189 I'm changing it to display the vendor ID/product ID as a backup if the name is blank, which will address the blank output you have.
