### ISSUE TITLE
Improve sample output on README

### ISSUE THREAD

**Issue by dbwiddis** [dblock/oshi#162]
The sample test output on the README is becoming long and spammy.  There's a ton of duplication across platforms (by design!) and the text-based presentation arguably isn't the best.

It seems pretty simple to parse the output into a [JTree](https://docs.oracle.com/javase/tutorial/uiswing/components/tree.html) and offer that (or a screenshot) for display... it's a natural extension of the existing JSON output to a simple GUI.

**Comment by dblock** [comment]
The cool kids are making animated GIFs these days, it could scroll over a small window :)

**Comment by dbwiddis** [comment]
Or I could just post links like here: http://codebeautify.org/jsonviewer/cb2ab86d

**Comment by dbwiddis** [comment]
<img align="right" src="https://dl.dropboxusercontent.com/u/41603526/samplejson.png" />The [http://jsonviewer.stack.hu/](http://jsonviewer.stack.hu/) site has the prettiest display I've seen so far, for image screen captures.  I like this for a static image display.  Not sure we need to give readers an interactive display, though... could simply say we provide JSON with the image, and describe how to poll at intervals to get CPU usage, etc.    I think I'll go this route....

**Comment by dbwiddis** [comment]
I think I have a format I like.  @dblock can you give a thumbs up?

https://github.com/dbwiddis/oshi/blob/master/README.md

**Comment by dblock** [comment]
I don't have a strong opinion!

**Comment by dbwiddis** [comment]
Sounds like a thumbs up!
