### ISSUE TITLE
GPU info

### ISSUE THREAD

**Issue by kamenitxan** [dblock/oshi#17]
Hi,
I have implemented basic GPU info for OSX (name, vendor and ram).
Now I have issues with linux because "lswh" command is not working on Travis https://travis-ci.org/kamenitxan/oshi/builds/47342070

Any idea how to fix it?

**Comment by dblock** [comment]
This is likely what will happen to many people who have XYZ linux/OSX flavor. Generally you should not rely on command line tools, especially not on linux. They all use some lower-level API to get this data.

**Comment by kamenitxan** [comment]
It would be possible to port lswh source to Java and read it from /proc.
In near future I will have not time for this, so anyone feel free to create pull request here: https://github.com/kamenitxan/oshi/tree/gpu-support

**Comment by dbwiddis** [comment]
Closing this as it's lingered for a year. #106 addressed some display issues which is probably as good as we're going to get for graphics.
