### ISSUE TITLE
Failed to create WbemLocator object. 

### ISSUE THREAD

**Issue by svilenvul** [dblock/oshi#172]
I have observed the following error message in the snapshot from 18.05.2016.

18:31:35.810 [ESH-safeCall-7] ERROR o.j.platform.windows.COM.WbemLocator - Failed to create WbemLocator object. Error code = 0x800401f0

What I am trying to do is 
```
SystemInfo systemInfo = new SystemInfo();
HardwareAbstractionLayer hal = systemInfo.getHardware();
operatingSystem = systemInfo.getOperatingSystem();
displays = hal.getDisplays();
fileStores = hal.getFileStores();
memory = hal.getMemory();
powerSources = hal.getPowerSources();
cpu = hal.getProcessor();
sensors = hal.getSensors();
networks = hal.getNetworkIFs();
drives = hal.getDiskStores();
if (cpu != null) {
      processes = cpu.getProcesses();
} 
```

I can not find a way to reproduce it 100% percent, but it occurs often.

I am running it on Windows 7 Enterprise Service Pack 1, with Intel Core i7-4712MQ 2.20 GHz.

If some other hardware or OS specific information is needed, please tell me, what do you need for the investigation.

**Comment by dbwiddis** [comment]
The `0x800401f0` error is "Failed to connect to server."  

The WMI queries that could cause this are for system serial number (`hal.getProcessor().getSystemSerialNumber()`), getting the disk hardware (`hal.getDiskStores()`) or many of the various sensors (`hal.getSensors()`).  You can probably figure out which one by looking at the serial # and sensor values for 'unknown' or 'zero' values.

The error may be associated with the COM object not being properly initialized. If I initialize for each query, I get errors that the security has already been set on the second attempt; I thought i had fixed the problem by creating a static initializer, but it appears now we may have the opposite problem.

I may go back to initializing for each query and ignoring errors with security already being set...

Does this occur on the first query? Does it only occur on repeated polling?  Does the frequency of polling affect it?

**Comment by dbwiddis** [comment]
On further research I think the problem may be associated with multithreading.   Only one thread is getting initialized, and if the request is made on another thread, it fails.  Looks like my static initializer solution won't work in a multithreaded environment.

**Comment by dbwiddis** [comment]
OK, after several failed experiments with synchronization, threading, and catching various errors, I've gone back to the COM initialization for each query with a boolean to enforce one-time security initialization on my branch, and updated the SNAPSHOT with the changes.  Let me know if that fixes your problems and I'll commit to the master.
