### ISSUE TITLE
CPU Temperature not correct for Intel NUC

### ISSUE THREAD

**Issue by hmerk** [dblock/oshi#173]
As the title says, I don't get correct CPU temp für my Intel NUC, sensors gives the following output:

coretemp-isa-0000
Adapter: ISA adapter
Core 0:       +41.0°C  (high = +105.0°C, crit = +105.0°C)
Core 1:       +41.0°C  (high = +105.0°C, crit = +105.0°C)

openHAB Systeminfo Binding (using oshi) just reports 0
As I understood the code, you are looking for
temp_input to read the actual temp. My intel Celeron shows temp2_input and temp3_input (one for each core).

**Comment by dbwiddis** [comment]
Can you list the contents of your `/sys/class/hwmon/hwmon` directory?  Is there simply no temp1_input file, but a temp2_input and temp3_input instead?   

Looking at the [documentation for sysfs](http://lxr.free-electrons.com/source/Documentation/hwmon/sysfs-interface), it appears the number corresponds to the location of the temperature sensor:
```
                1: CPU embedded diode
                2: 3904 transistor
                3: thermal diode
                4: thermistor
                5: AMD AMDSI
                6: Intel PECI
```
I guess I should check for all six.

**Comment by hmerk** [comment]
Here is my structure 
/sys/class/hwmon/
                             hwmon0/
                                           ~device
                                           /power
                                           ~subsystem
                                           name                            (this says coretemp)
                                           temp2_crit
                                           temp2_crit_alarm
                                           temp2_input
                                           temp2_label                (this says Core 0)
                                           temp2_max
                                           temp3_crit
                                           temp3_crit_alarm
                                           temp3_input
                                           temp3_label               (this says Core 1)
                                           temp3_max

So I guess it ist not the location....

**Comment by dbwiddis** [comment]
I think I'll check temp1, and if it doesn't exist, I'll iterate 2 thru 6 and average readings...

**Comment by dbwiddis** [comment]
I've added a fallback to average the readings of temp2 thru temp6 if temp1 doesn't exist in #175.  2.5-SNAPSHOT has been updated with the changes.

**Comment by hmerk** [comment]
Sorry, did not get a chance to test this earlier.
Thanks for your quick fix, it is working as expected :+1:

**Comment by dbwiddis** [comment]
Have you tested with the most recent snapshot as-of about a week ago?  I refactored all the WMI stuff and want to make sure I didn't re-introduce a bug.

**Comment by dbwiddis** [comment]
Erm, nevermind. Different change. Ignore that.
