### ISSUE TITLE
Serializing system information

### ISSUE THREAD

**Issue by joker1** [dblock/oshi#178]
The problem: Currently, HardwareAbstractionLayer and OperatingSystem (and all implementing classes) are not serializable. This makes it unnecessarily difficult to pass them as a parameter with RMI (or Apache Tribes or any other communication framework that relies on serialization).

Solution: make all classes implementing HardwareAbstractionLayer or OperatingSystem (+ all classes that are used as class attributes) serializable by implemeting java.io.Serializable.

**Comment by dbwiddis** [comment]
Sounds like a great change.  Are you able to make the updates and submit a pull request?
