### ISSUE TITLE
os version looks odd

### ISSUE THREAD

**Issue by jorgheymans** [dblock/oshi#183]
Hi,

We moved one of our applications using oshi to a new linux machine, and now the os version string looks a bit odd

SystemInfo.getOperatingSystem().toString() :
```
GNU/Linux LSB_ =base-4.0-amd64:base-4.0-ia32:base-4.0-noarch:core-4.0-amd64:core-4.0-ia32:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-ia32:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-ia32:printing-4.0-noarch (LSB_VERSION=base-4.0-amd64:base-4.0-ia32:base-4.0-noarch:core-4.0-amd64:core-4.0-ia32:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-ia32:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-ia32:printing-4.0-noarch) build 2.6.32-573.7.1.el6.x86_64
```

(we're using 2.4)

**Comment by dbwiddis** [comment]
This is what you get when I have to guess at (and read lots of online docs about) what's in various files on various flavors of Linux. :-)

Let me describe what OSHI does, and you can tell me where it went wrong.

First, it looks for the release filename, getting the first of:
- `/etc/os-release`
- `/etc/lsb-release`
- Any `/etc/*-release`, `/etc/*-version`,  `/etc/*_release`, `/etc/*_version`
- `/etc/release`
- `/etc/issue`

Second, it parses the file it found in the previous step, looking for standard (?) os-release or lsb-release formats.  For the distribution name:
- It looks for a NAME or DISTRIB_ID field (e.g., NAME="Ubuntu")
- Failing the above, it reads the first line of the above file looking for the word "release" or "VERSION" and taking the part of the text before that word
For the distribution version:
- It looks for a VERSION_ID or DISTRIB_RELEASE field (e.g., VERSION_ID="14.04") to set the version
- It looks for a DISTRIB_CODENAME or VERSION field to set the codename
- Failing the above, it reads the first line of the above file looking for the word "release" or "VERSION" and taking the part of the text after that word
- Failing all of that, it reads the `os.version` system property
- It sets the build number from `/proc/version`

So, looking at your string:
- It looks like it found a file (possibly one of the first two) but failed the first two checks but then found a string "LSB_VERSION=base-4.0..." and that met the rules for parsing before and after "VERSION" and set your OS name to "LSB_" and version to "=base-4.0...", and set the codename to the entire string.

To fix:
- I can probably easily change the checks for "VERSION" and "release" to pad with spaces. That would avoid this odd behavior but not get your actual version number.

What I need from you:
- Please tell me what your release file is named (/etc/*-release or similar).
- Please quote the entire contents of that file. Or, at least the lines that would include the version name (e.g., Ubuntu or Red Hat), number (14.04), and codename (Trusty Tahr).

**Comment by dbwiddis** [comment]
Also in addition to the above, the output of the command `lsb_release` would be useful if it's not exactly the same as the file contents.

**Comment by dbwiddis** [comment]
OK, a little sleuthing and I'm pretty sure I know the problem.  [The `lsb-release` file](http://linux.die.net/man/1/lsb_release) actually provides overrides for the parsing of the *-release file.  So I actually have to read them both to properly do this.

I'm guessing you have an `lsb-release` file with only the LSB_VERSION line and no others.  And you also have a `*-release` file for your distribution with the format `Distributor release x.x (Codename)` that isn't getting looked at.

**Comment by jorgheymans** [comment]
Sadly i have no shell access to our hosted environments so the only thing i can do (as i did last time) is try out snapshots :-|

**Comment by dbwiddis** [comment]
OK, I've completely rebuilt the parsing routines and hope I've covered everything.  Try the latest snapshot.
https://oss.sonatype.org/content/repositories/snapshots/com/github/dblock/oshi-core/2.5-SNAPSHOT/oshi-core-2.5-20160603.212728-25.jar

**Comment by jorgheymans** [comment]
@dbwiddis i can confirm that with 2.5 this is fixed , many thanks !

**Comment by dbwiddis** [comment]
Excellent!  I'm curious what the final version (as parsed) is? :)

**Comment by jorgheymans** [comment]
it looks like this now, pretty neat :
```
GNU/Linux Red Hat Enterprise Linux Server x.x (Santiago) build x.x.xx-xxx.x.x.el6.x86_64
```

where x is a bunch of number i have replaced for reason of not disclosing our exact server version :-|

However, it does seem that 2.5 is jdk 1.8 only now, was this intentional ? From the manifest:

```
X-Compile-Target-JDK: 1.8
```

**Comment by jorgheymans** [comment]
@dbwiddis do you want me to create a new issue for this ?

**Comment by dbwiddis** [comment]
The move to Java 8 was intentional (and in the changelog).   The primary reason for the move is that I needed to do date/time parsing as part of the Process code, and Java 7's SimpleDateFormat wasn't thread safe.   There were some gyrations I could jump through to make it work, and if anyone truly needs Java 7 support I'll consider doing such.  However, Java 8 has been out over 2 years now, and Java 7 is over a year past its EOL, so I reasoned that unless specifically asked, I would support Java 8 going forward.    I gain a few other nice toys to make my code-writing life easier (sorting with streams, getOrDefault with maps, etc.) and would much prefer to stay on Java 8.

**Comment by jorgheymans** [comment]
OK for the moment I will stick to 2.4 then, perhaps towards the end of the year we will transition to jdk1.8

**Comment by dbwiddis** [comment]
It's not too hard to make a 1.7 port of 2.5 if you desire it.  I'd simply add another dependency to the [threeten project](http://www.threeten.org/) and undo some of the other Java 8 conveniences I've created.   Honestly the 1.8 decision was a coin flip vs. adding another dependency.  Given the source and binary compatibility, I didn't think there was much of a hurdle of moving up...

**Comment by jorgheymans** [comment]
Thanks for considering this, i will leave the decision entirely up to you. 

Our applications are often long-lived (10+ years) so a jdk EOL does not mean much to us because the application server version is still tied to it.

**Comment by dbwiddis** [comment]
I'm working on a couple other issues that may result in a 2.5.1.  I'll plan to release a java7 version of that as the final oshi java 7, so you can at least get all the latest updates.

**Comment by jorgheymans** [comment]
that's superb many thanks !

**Comment by dbwiddis** [comment]
OK, so there is now a 2.5.1 release and a 2.5.1-java7 release.  No promises I'll keep this up past 2.5.* but at least you can get all the current goodies.

**Comment by jorgheymans** [comment]
deployed and tested, everything works great !

In terms of jdk7 i would say for our purposes you don't need to stay compatible anymore going forward. With this fix our monitoring screen works perfectly now and we don't plan to move to other hardware for the next couple of years.

**Comment by dbwiddis** [comment]
FYI, I just did do a 2.6-m-java7 release with some fixes/improvements, although the only Linux change is addition of volume name and UUID to the FileStore so you're probably fine where you are with 2.5.1.

Due to my inability to convince the Central Repository to respect my versioning scheme, I'm officially giving up dual releases so that's officially the last Java7 release.

**Comment by jorgheymans** [comment]
no worries thanks a lot for your efforts :-)
