### ISSUE TITLE
Failed to getCpuTemperature() in Windows

### ISSUE THREAD

**Issue by svilenvul** [dblock/oshi#185]
I have noticed this issue since 2.4 release maybe, but I was not sure what fails, because no error message is logged. 
I think I have a clue now. Unfortunately the issue occurs not so often (let's guess in 1 of 10 executed tests.) 

First I am calling:

```
        HardwareAbstractionLayer hal = systemInfo.getHardware();
        operatingSystem = systemInfo.getOperatingSystem();
        ...
        sensors = hal.getSensors();
```
and then:
```
public DecimalType getSensorsCpuTemperature() {
        BigDecimal cpuTemp = new BigDecimal(sensors.getCpuTemperature());
        cpuTemp = cpuTemp.setScale(PRECISION_AFTER_DECIMAl_SIGN,  BigDecimal.ROUND_HALF_UP);
        return new DecimalType(cpuTemp);
}
```
I have a test method, that basically is checking if this method returns.

When the test passes, I see console output like:

```
10:37:40.415 [ESH-thingHandler-3] DEBUG oshi.util.platform.windows.WmiUtil - Connected to root\cimv2 WMI namespace
10:37:40.416 [ESH-thingHandler-3] DEBUG oshi.util.platform.windows.WmiUtil - Query: SELECT CurrentReading FROM Win32_Temperature 
10:37:40.432 [ESH-thingHandler-3] DEBUG oshi.util.platform.windows.WmiUtil - Connected to root\cimv2 WMI namespace
10:37:40.433 [ESH-thingHandler-3] DEBUG oshi.util.platform.windows.WmiUtil - Query: SELECT CurrentReading FROM Win32_TemperatureProbe 
10:37:40.443 [ESH-thingHandler-3] DEBUG oshi.util.platform.windows.WmiUtil - Connected to root\cimv2 WMI namespace
10:37:40.443 [ESH-thingHandler-3] DEBUG oshi.util.platform.windows.WmiUtil - Query: SELECT Temperature FROM Win32_PerfFormattedData_Counters_ThermalZoneInformation 
10:37:40.454 [ESH-thingHandler-3] DEBUG oshi.util.platform.windows.WmiUtil - Connected to root\wmi WMI namespace
10:37:40.455 [ESH-thingHandler-3] DEBUG oshi.util.platform.windows.WmiUtil - Query: SELECT CurrentTemperature FROM MSAcpi_ThermalZoneTemperature 
```
When the test fails the last query is not executed:
```
10:27:41.626 [ESH-thingHandler-3] DEBUG oshi.util.platform.windows.WmiUtil - Connected to root\cimv2 WMI namespace
10:27:41.627 [ESH-thingHandler-3] DEBUG oshi.util.platform.windows.WmiUtil - Query: SELECT CurrentReading FROM Win32_Temperature 
10:27:41.722 [ESH-thingHandler-3] DEBUG oshi.util.platform.windows.WmiUtil - Connected to root\cimv2 WMI namespace
10:27:41.722 [ESH-thingHandler-3] DEBUG oshi.util.platform.windows.WmiUtil - Query: SELECT CurrentReading FROM Win32_TemperatureProbe 
10:27:41.742 [ESH-thingHandler-3] DEBUG oshi.util.platform.windows.WmiUtil - Connected to root\cimv2 WMI namespace
10:27:41.742 [ESH-thingHandler-3] DEBUG oshi.util.platform.windows.WmiUtil - Query: SELECT Temperature FROM Win32_PerfFormattedData_Counters_ThermalZoneInformation 
```
I guess that some Exception might occur in [WindowsSensors@getCpuTemperature()]( https://github.com/dblock/oshi/blob/c44e9520ce7997e50641587f6746986ab95d3205/src/main/java/oshi/hardware/platform/windows/WindowsSensors.java#L88), but as I sad, no error message is logged .

**Comment by dbwiddis** [comment]
I'm really starting to hate the Windows sensor code. 😠 

Some questions for you:
- What do you mean by "checking if this method returns"?  It is intended to return 0 if it fails, and it stores its old value to return in that case, so once you get at least one reading it should be robust to intermittent errors.  It still might fail the test the first time, for a variety of reasons (including simple latency).  So is it returning 0 or crashing?
- Can you manually execute that problematic query (repeatedly) and inspect the results and see if you see anything unusual?  (The windows command line would be `wmic path=Win32_PerfFormattedData_Counters_ThermalZoneInformation get Temperature`)

I can throw in a few more debug statements as well, to try to narrow down the problem.

**Comment by svilenvul** [comment]
> What do you mean by "checking if this method returns"? It is intended to return 0 if it fails, and it stores its old value to return in that case, so once you get at least one reading it should be robust to intermittent errors. It still might fail the test the first time, for a variety of reasons (including simple latency). So is it returning 0 or crashing?

It is crashing. I could try to catch an Exception to see  more details.

> Can you manually execute that problematic query (repeatedly) and inspect the results and see if you see anything unusual? (The windows command line would be wmic path Win32_PerfFormattedData_Counters_ThermalZoneInformation get Temperature)

Ok I will try it out.

**Comment by dbwiddis** [comment]
An exception/stack trace would be awesome. I've traced through the code multiple times and don't see anything obvious.

**Comment by svilenvul** [comment]
I can not catch any Throwable object from getCpuTemperature().

The command line result is:
```
C:\prj\openHAB\EclipseIDE\git\openhab2-addons>wmic path Win32_PerfFormattedData_Counters_ThermalZoneInformation get Temperature
ERROR:
Description = Not found
```

**Comment by svilenvul** [comment]
`C:\prj\openHAB\EclipseIDE\git\openhab2-addons>wmic /namespace:\\root\wmi PATH MSAcpi_ThermalZoneTemperature get CurrentTemperature
CurrentTemperature
3312
3232`

**Comment by svilenvul** [comment]
C:\prj\openHAB\EclipseIDE\git\openhab2-addons> wmic /namespace:\\root\wmi PATH MSAcpi_ThermalZoneTemperature get CurrentTemperature
CurrentTemperature
3312
3232

**Comment by svilenvul** [comment]
I guess it is some sort of timing issue - the operation takes too long, when it is executed first time after several minutes. I will close the issue.

**Comment by dbwiddis** [comment]
Is the "takes too long" a timeout thing that's in your code or in oshi?  If oshi is crashing, exception or not, that's a bug that needs to be fixed.

**Comment by svilenvul** [comment]
It is not crashing, just in the test I expected that the time that will take to return from getCpuTemperature() will be relative constant, but is not. Every first time that this method is called after let's say 30 minutes (approximately) it takes significantly longer to return.

**Comment by dbwiddis** [comment]
Ah, got it.  Yeah, mine is sometimes slow the first time as well.  A brief web search indicates this is a common problem with no known solution...
