### ISSUE TITLE
Release Next

### ISSUE THREAD

**Issue by KVqVuo6Z** [dblock/oshi#19]
Your link to download Oshi in your README is out-of-date (http://code.dblock.org/downloads/oshi/oshi-1.1.zip).

I spent a lot of time debugging apparent incompatibilities between the archived Oshi Core JAR file and OS X Yosemite. A closer look at your source files and commit history showed clear support for OS X, and I was able to build an up-to-date, OSX-compatible JAR with Maven after I checked out the project.

I would hate for your project to lose some potential users due to this issue. Thanks!

**Comment by dblock** [comment]
Yeah, my website stuff moved & al. I can re-upload it somewhere, but really what we need is a maven release, cc: @ptitvert, care to do it?

**Comment by ptitvert** [comment]
Will try to do it. (To be honest never did it, so need to understand a 
bit how to do it :-) tha't why I said "try" !!!)

:-)

**Comment by dblock** [comment]
Thanks! As you do it, try to author a RELEASING.md similar to [Waffle's](https://github.com/dblock/waffle/blob/master/Docs/MavenReleaseGuide.md) and commit it here.

**Comment by dblock** [comment]
Also a good RELEASING.md is https://github.com/intridea/grape-entity/blob/master/RELEASING.md, maybe start with that one (it talks about general things first).

**Comment by dblock** [comment]
Bump @ptitvert

**Comment by dbwiddis** [comment]
I've done a release of 1.2 and learned a lot along the way!   The pom.xml is updated to make future releases rather smooth, committers just need a gpg key and Central Repository credentials added to be able to do the same.
