### ISSUE TITLE
Please tag v1.1 and ideally add a release

### ISSUE THREAD

**Issue by chewi** [dblock/oshi#20]
…so that Linux distributions can package this properly. The zip mentioned in the README has no source files. See [here](https://help.github.com/articles/creating-releases/) for more info.

**Comment by dblock** [comment]
See https://github.com/dblock/oshi/issues/19, @ptitvert said he was going to do it :)

**Comment by chewi** [comment]
I thought he was just talking about Maven. A Maven source release is better than nothing but it tends to lack extras like tests.

**Comment by ptitvert** [comment]
I'm bit late in that regard... Sorry
I'll try to do asap
