### ISSUE TITLE
Support for ARM-64 computers

### ISSUE THREAD

**Issue by dmcwhinnie** [dblock/oshi#204]
I am using this on the Pine 64, with  32-bit java.  This is running as part of the add-on to OpenHab.  In this scenario the udev library is not found.  I had to install the 3-bit library, but also had to link some files and directories so the library could be found.

Error:

>  Unable to load library 'udev': Native library (linux-arm/libudev.so) not found in resource path 

Current work around:

1. Install the 32-bit library

`apt-get install udev:armhf`

2. Create link for the 32-bit folder. Files are installed in /lib/arm-linux-gnueabihf, but OSHI is looking in /lib/linux-arm

` ls -s /lib/arm-linux-gnueabihf/ /lib/linux-arm`

3. Create the .so link. (install created the .so.1 file)
` ln -s /lib/linux-arm/libudev.so.1 /lib/linux-arm/libudev.so`

Link to the OpenHab Issue.

https://community.openhab.org/t/systeminfo-initialization-error-on-pine64/11726/9

**Comment by dbwiddis** [comment]
Unfortunately the answer is not trivial.  All OSHI does is call JNA's [Native.loadLibrary()](http://java-native-access.github.io/jna/4.2.1/com/sun/jna/Native.html#loadLibrary-java.lang.Class-) method:
```
Udev INSTANCE = (Udev) Native.loadLibrary("udev", Udev.class);
```
... trusting JNA to find the library.  Here's what the javadoc says:

> A search for a given library will scan the following locations:
> - jna.library.path User-customizable path
> - jna.platform.library.path Platform-specific paths
> - On OSX, ~/Library/Frameworks, /Library/Frameworks, and /System/Library/Frameworks will be searched for a framework with a name corresponding to that requested. Absolute paths to frameworks are also accepted, either ending at the framework name (sans ".framework") or the full path to the framework shared library (e.g. CoreServices.framework/CoreServices).
> - Context class loader classpath. Deployed native libraries may be installed on the classpath under ${os-prefix}/LIBRARY_FILENAME, where ${os-prefix} is the OS/Arch prefix returned by Platform.getNativeLibraryResourcePrefix(). If bundled in a jar file, the resource will be extracted to jna.tmpdir for loading, and later removed (but only if jna.nounpack is false or not set).
> 
> You may set the system property jna.debug_load=true to make JNA print the steps of its library search to the console.

There are a few ways I could tweak OSHI to search elsewhere, e.g., [NativeLibrary.addSearchPath()](http://java-native-access.github.io/jna/4.2.1/com/sun/jna/NativeLibrary.html#addSearchPath-java.lang.String-java.lang.String-) specifically for udev, or setting the `jna.library.path` internally; however I think it's preferable to leave that property as a command-line option.  It looks like you could specify your path on the java command line, e.g., 
```
java -Djna.library.path=<path to your libc and libudev> ClassThatStartsOpenHab
```

I think the long-term fix is to add the ARM-64 path to JNA's [loadLibrary()](https://github.com/java-native-access/jna/blob/master/src/com/sun/jna/NativeLibrary.java) searching.

So, all that said... I feel like a middleman between your platform and JNA. While I could band-aid your specific problem in OSHI I am not sure that's the best route.  I'll keep looking at this...

**Comment by dmcwhinnie** [comment]
Thanks for pointing me in the right direction.  Looking through the JNA code, it seems the OS isn't configured correctly to find the library.  It should be dynamic....

The [NativeLibrary.java](https://github.com/java-native-access/jna/blob/master/src/com/sun/jna/NativeLibrary.java) shows it should use ldconfig to look for the library.  So I believe there must be an issue there.


             // We might be wrong with the multiArchPath above. Raspbian,
            // the Raspberry Pi flavor of Debian, for example, uses
            // uses arm-linux-gnuabihf since it's using the hard-float
            // ABI for armv6. Other distributions might use a different
            // tuple for the same thing. Query ldconfig to get the additional
            // library paths it knows about.

**Comment by dbwiddis** [comment]
Sounds like you may have a better idea what to do than I do (and a box to test on as well.)  I'll stand by to make any changes you think are prudent.  You may get some help on the JNA mailing list as well.

**Comment by dmcwhinnie** [comment]
The code in JNA which does the library look up was modified for version 4.2.2, OpenHab is using 4.2.1.  So that may be the issue. I'm no java programmer, so don't know for sure.

It appears the issue is that in new Ubuntu versions there is no libudev0, only libudev1.  so in /lib I have a libudev.so.1.  If I create a libudev.so or a libudev.so.0 then it works.  I am thinking the changes to the library lookup part of the JNA code dill fix this. 

So at this point, I think I will try to get JNA version 4.2.2 in place before moving forward.  In any case, I think it is safe to say this is not an OSHI issue.
