### ISSUE TITLE
Question: ETA for release 3.0?

### ISSUE THREAD

**Issue by brettwooldridge** [dblock/oshi#217]
I just picked up this project, trying to replace sigar, but ran into a snag.  The front-page shows this output from ``SystemInfoTest``:
```
Processes: 401, Threads: 1159
   PID  %CPU %MEM       VSZ       RSS Name
 55977  27.9  0.2   6.8 GiB  34.3 MiB java
 51820  18.7  5.6   6.3 GiB 919.2 MiB eclipse
 39272  11.2 17.8   7.1 GiB   2.8 GiB prl_vm_app
 85316   6.5  2.9   5.6 GiB 471.4 MiB thunderbird
 35301   5.4  0.5   1.7 GiB  89.8 MiB Microsoft Excel
```
Which is exactly what I need -- CPU-per-process.  I started coding up the change but soon encountered the fact that ``OperatingSystem`` does not provide the required method ``getProcesses()``.  Appearently that is a 3.0 thing.

Any ETA on the 3.0 release?

**Comment by dbwiddis** [comment]
Can I give an ETA and then double it like most software? 😀 

I'll tell you that I'm targeting sometime this coming weekend, but that's dependent on how much time I have after meeting day-job deadlines this week.  I'm closing in on the new properties configuration code and still need to consider options and possibly choose a replacement for the javax.json framework.  And, of course, the long pole in the tent will be tests.  I may push a release candidate if I can't get to the tests immediately.

The `getProcesses()` method in 2.x was on the `CentralProcessor` object (with no parameters, so you got the whole list unsorted and had to build your own comparator).  I believe the API on the site still points to the 2.6.2 docs for your reference.  The [UPGRADING](https://github.com/dblock/oshi/blob/master/UPGRADING.md) document is up to date with the current changes.

Or you can use the current 3.0-SNAPSHOT that has the methods you need.  The `oshi-core` portion of the release is pretty stable at this point.

**Comment by dbwiddis** [comment]
So I decided to leave the existing json framework alone, which means code's essentially done.  I still need to write a lot more tests but I'm going to try to push a release candidate right now.  Hopefully it'll suit your needs.

**Comment by dbwiddis** [comment]
Well... ran into some problems with the release and found a bug, so a bit longer.... sorry :)

**Comment by brettwooldridge** [comment]
No problem, we all encounter release delays.  The original question was really a June/July/August kind of question.

**Comment by dbwiddis** [comment]
Early July is a pretty reasonable answer, highly dependent on me either learning Maven or bribing a Maven expert to help with #200.

**Comment by dbwiddis** [comment]
Finally managed to get 3.0-rc1 out to maven.   I'll be updating docs and writing tests and such before the final release, but you're probably safe to develop to this. Closing this issue.
