### ISSUE TITLE
Solaris port

### ISSUE THREAD

**Issue by dbwiddis** [dblock/oshi#227]
Installed a Solaris VM to see how much of the existing Linux code could be reused on Unix.

What works:
```
Unix/SunOS Solaris 5.11
CPU Load (8.9%) (OS MXBean)
Load Averages 0.42 0.43 0.41
Processes: 114
Network interfaces:
 Name: net0 (net0)
  MAC Address: 00:1c:42:3b:ca:aa
  MTU 1500, Sped 0 bps
  IPv4: [10.211.55.11]
  IPv6: [fec0:0:0:fea9:21c:42ff:fe3b:caaa, fe80:0:0:21c:42ff:fe3b:caaa]
  Traffic: received ?/?, transmitted ?/?
```
What doesn't work:

Everything else. 😆 

Digging around it looks like one can get a fair bit of information by parsing command lines.

- [Solaris docs](https://docs.oracle.com/cd/E23824_01/html/821-1451/gkkwk.html) for many commands.
- More [Solaris docs](https://docs.oracle.com/cd/E23824_01/html/821-1459/docinfo.html#scrolltoc) for filesystem, usb, swap.
- mpstat appears to give cpu ticks (reports %, multiply by time since boot or last command to get ticks)
- prtdiag
- prtconf
- swap -l
- df

**Comment by henryx** [comment]
Solaris (and FreeBSD) are much POSIX compatible, so, is more correct to try
the OS X code instead of Linux code

2016-07-03 7:24 GMT+02:00 dbwiddis <notifications@github.com>:

**Comment by dbwiddis** [comment]
Except the OS X code largely relies on Darwin frameworks, not POSIX/BSD.  

Fortunately the Unix stuff will be largely portable from Solaris to other platforms once that part's done.

**Comment by dbwiddis** [comment]
```
[main] INFO oshi.SystemInfoTest - Initializing System...
Oracle Solaris 5.11
Intel(r) Core(TM) i7-2820QM CPU @ 2.30GHz
 1 physical CPU(s)
 2 logical CPU(s)
Identifier: x86 Family 6 Model 42 Stepping 7
Serial Num: Parallels-45 2E 7E 2D 57 5C 4B 59 B1 30 28 81 B7 81 89 34
Uptime: 0 days, 07:55:16
CPU, IOWait, and IRQ ticks @ 0 sec:[8225609, 0, 10186, 26203776, 0, 0, 0]
CPU, IOWait, and IRQ ticks @ 1 sec:[8225882, 0, 10186, 26206577, 0, 0, 0]
User: 8.9% Nice: 0.0% System: 0.0% Idle: 91.1% IOwait: 0.0% IRQ: 0.0% SoftIRQ: 0.0%
CPU load: 6.6% (counting ticks)
CPU load: 21.7% (OS MXBean)
CPU load averages: 0.15 0.12 0.14
CPU load per processor: 4.9% 3.9%
```

**Comment by dbwiddis** [comment]
Making progress!  CPU, memory, OS, and Processes are done...
On to filesystem, disks, sensors... the fun stuff!
```
Oracle Solaris 5.11 (SunOS) build 11.3
Intel(r) Core(tm) i7-2820QM CPU @ 2.30GHz
 1 physical CPU(s)
 2 logical CPU(s)
Identifier: x86 Family 6 Model 42 Stepping 7
Serial Num: Parallels-45 2E 7E 2D 57 5C 4B 59 B1 30 28 81 B7 81 89 34
Memory: 309.3 MiB/2.0 GiB
Swap used: 369.2 MiB/1024.0 MiB
Uptime: 0 days, 22:57:26
CPU, IOWait, and IRQ ticks @ 0 sec:[18335713, 0, 11306, 61748263, 0, 0, 0]
CPU, IOWait, and IRQ ticks @ 1 sec:[18337124, 0, 11308, 61751629, 0, 0, 0]
User: 29.5% Nice: 0.0% System: 0.0% Idle: 70.4% IOwait: 0.0% IRQ: 0.0% SoftIRQ: 0.0%
CPU load: 20.6% (counting ticks)
CPU load: 29.4% (OS MXBean)
CPU load averages: 0.50 0.29 0.16
CPU load per processor: 6.0% 35.0%
Processes: 116, Threads: 635
   PID  %CPU %MEM       VSZ       RSS Name
 10779  23.5  0.0 197.4 KiB 100.8 KiB java
 10782  16.7  0.0 122.8 KiB  47.7 KiB java
 10636  14.1  0.0 379.4 KiB 167.2 KiB firefox
  7700   1.1  0.0   2.6 MiB 695.4 KiB java
  4244   0.8  0.0 187.8 KiB  59.2 KiB java
  2442   0.4  0.0 186.1 KiB  91.4 KiB Xorg
    15   0.1  0.0  32.4 KiB     2 KiB svc.configd
  7232   0.1  0.0 133.4 KiB   8.2 KiB gnome-terminal
     3   0.1  0.0   0 bytes   0 bytes fsflush
     5   0.1  0.0   0 bytes   0 bytes zpool-rpool
```

**Comment by dbwiddis** [comment]
> Oracle Solaris 5.11 (SunOS) build 11.3

Or should be Oracle SunOS 5.11 (Solaris) build 11.3?  Versioning is weird.

**Comment by dblock** [comment]
OMG you're doing a Solaris port?! I used to love working on a Sun Sparc machine in the 90s :)

SunOS is until version 4.
Solaris is after version 5.

In your example it's Solaris 5.11 (SunOS), for older versions are just SunOS I think.

**Comment by dblock** [comment]
Also, https://github.com/dblock/alkaline/blob/master/config.guess#L325 might be useful or confusing depending on how you look at it. I can't wait for a MiNT port!

**Comment by dbwiddis** [comment]
> OMG you're doing a Solaris port?! 

I'm trying. 😄   [Motivation here](http://stackoverflow.com/questions/38103714/howto-get-list-of-running-processes-in-java-using-jna-in-a-cross-platform-enviro/38114727). Some things don't work on a VM so I'm having to read online samples to guess at outputs, etc.  

I'm also relying heavily on command line (particularly `kstat`) rather than native code, at least for the time being, littering the code with a bunch of TODOs for later.

> SunOS is until version 4.
> Solaris is after version 5.

Technically true, but [this non-authoritative source](https://kb.iu.edu/d/agjq) says "SunOS is a Sun Microsystems implementation of the Unix operating system. **Solaris is SunOS packaged with a number of additional tools** and a graphical user interface (GUI) environment."  Supporting this, the output of `uname -a` still identifies it as SunOS: `SunOS oshi 5.11 11.3 i86pc i386 i86pc` where 5.11 is the 'version' and 11.3 is the 'release'.

So I'm thinking it's still correct to set the "family" as SunOS (the other "family" alternative would be "Unix" or maybe "Unix/SunOS") and use Solaris as the "code name".  It'd be incorrect to say Solaris version 5.11 and since the 11.3 is a more specific versioning I think that's the best way to do it.

> I can't wait for a MiNT port!

You'll wait, until I can get a VM for it 😈

**Comment by dbwiddis** [comment]
Today's progress...
```
Sensors:
 CPU Temperature: 0.0°C
 Fan Speeds:[]
 CPU Voltage: 0.0V
Power: 0:00 remaining
 BST0 @ 0.0%
Disks:
 cmdk0: (model: Solaris 11.3-0 - S/N: N5HYXGAQTHF459E) size: 137.4 GB, reads: 47.7 GiB, writes: 13.9 GiB 
 sd0: (model: Virtual DVD-ROM - S/N: ) size: 1.2 GB, reads: 700.8 KiB, writes: 0 bytes 
File System:
 File Descriptors: 1859/2090
 solaris (Local Disk) [zfs] 114.7 GiB of 119.9 GiB free (95.7%) is rpool/ROOT/solaris and is mounted at /
 Oracle_Solaris-11_3-Live-X86 (Local Disk) [hsfs] 0 bytes of 1.1 GiB free (0.0%) is /dev/dsk/c1t1d0s2 and is mounted at /media/Oracle_Solaris-11_3-Live-X86
Network interfaces:
 Name: net0 (net0)
   MAC Address: 00:1c:42:3b:ca:aa 
   MTU: 1500, Speed: 1 Gbps 
   IPv4: [10.211.55.11] 
   IPv6: [fec0:0:0:fea9:21c:42ff:fe3b:caaa, fe80:0:0:0:21c:42ff:fe3b:caaa] 
   Traffic: received 676855 packets/842.6 MiB; transmitted 316893 packets/20.6 MiB
```
Only displays and USB devices left!

**Comment by dbwiddis** [comment]
Done in #229
