### ISSUE TITLE
Free memory vs. Available memory

### ISSUE THREAD

**Issue by dbwiddis** [dblock/oshi#23]
GlobalMemory.getAvailable() only reports "free" memory for Mac and Linux implementations.  Unfortunately, this is rarely useful except immediately upon reboot.  After a short period of usage, free drops to near-zero and much of the memory released by programs resides in a cache for easy access.

Available memory includes both "free" memory (never used or purged) and "inactive" (Mac/Linux) or "standby" (Windows) memory.

The Windows implementation of getAvailable() correctly uses GlobalMemoryStatusEx()'s ullAvailPhys value, which includes both free and standby memory in its total. 

For the mac branch (vm_stat) you would need to add the value of "Pages inactive:" to the existing "Pages free:" calculation.  For linux (proc/meminfo), you need to add the value returned by "Inactive:" to the existing  "MemFree:" or "MemAvailable:".

**Comment by dblock** [comment]
This makes a lot of sense, @dbwiddis please feel free to contribute.

**Comment by dbwiddis** [comment]
Contributing would require:
1. A decision from you as to whether you want additional methods.  For example, SIGAR has getFree() (free+cached) and getActualFree() which reports the (not useful) non-cached free memory.    But you only have a single method getAvailable().   And the Windows port only returns that one combined number.
2. I have zero experience with git, and pull requests, etc.   I can get a copy with subversion and create a diff if that's helpful.
3. I'm intereested in learning more about JNA and would prefer to actually try to rewrite these methods using JNA calls instead of command-line parsing.

All that said, the fix should be an easy string edit as I outlined in the issue until I get to steps 2 and 3, myself.

**Comment by dbwiddis** [comment]
Figured out how to make a pull request. I feel accomplished.

**Comment by dblock** [comment]
I think we want the lowest common denominator, so it sounds like `getAvailable()`.

I would more than welcome a rewrite using low level JNA calls.

**Comment by dblock** [comment]
@dbwiddis :+1: on the PR workflow, congrats on contributing to open-source!

**Comment by dbwiddis** [comment]
Changelog done. Trying to figure out how to squash commits (I know the command line 'rebase' version but I've been interacting with the repository via svn or github website, so steep learning curve here!)

**Comment by dbwiddis** [comment]
Decided just to close the old PR and create a new one with all the changes in one commit (except for linking #25 to the changelog)

**Comment by alextinng** [comment]
so how can I get linux/mac "free" memory?

**Comment by dbwiddis** [comment]
Depends what you mean by "free".  OSHI's "available" returns memory that is, for all intents and purposes, "free" for you to use; it's just been used before and recycled.

If you want an amount that matches `top` or `free` or `vmstat` (which slowly drops to near-zero the longer your system is up, and is largely a useless stat) then you could:

If Using the Oracle JVM, `import com.sun.management.OperatingSystemMXBean` and then use its `getFreePhysicalMemorySize()` method.

Otherwise, you could do this in OSHI:
```
        List<String> memInfo = FileUtil.readFile("/proc/meminfo");
        for (String checkLine : memInfo) {
            String[] memorySplit = ParseUtil.whitespaces.split(checkLine);
            if (memorySplit.length > 1 && "MemFree:".equals(memorySplit[0])) {
                long memory = ParseUtil.parseLongOrDefault(memorySplit[1], 0L);
                if (memorySplit.length > 2 && "kB".equals(memorySplit[2])) {
                    memory *= 1024;
                }
                return memory;
            }
        }
        return 0L;
```

**Comment by alextinng** [comment]
"Free" and "Available" memory is different things, I searched in the internet and found most of the time, customer just want to get free memory, so should there be a method for getting free memory?
