### ISSUE TITLE
Feature request: dynamic informations about physical drives

### ISSUE THREAD

**Issue by lundefugl** [dblock/oshi#233]
At first: it's a great library and very simple to use. Thanks.

For the HWDiskStore object we would like have some additional informationen.

- the usage in percent
- the OSFileStore objects which can be associated with the HWDiskStore

At the moment we use under Windows a own implementation with OSHI-wmi-calls:

```
final Map<String, List<String>> perfData = WmiUtil.selectStringsFrom(null, "Win32_PerfFormattedData_PerfDisk_PhysicalDisk", "Name,PercentDiskTime,PercentIdleTime,DiskBytesPerSec", null);

 final Map<String, List<String>> diskPartitions = WmiUtil.selectStringsFrom(null, "Win32_DiskPartition", "Name,DeviceID", null);
final Map<String, List<String>> disk2Partition = WmiUtil.selectStringsFrom(null, "Win32_DiskDriveToDiskPartition", "Antecedent,Dependent", null);
final Map<String, List<String>> logicalDiskToPartition = WmiUtil.selectStringsFrom(null, "Win32_LogicalDiskToPartition", "Antecedent,Dependent", null);
```

We think: a integration in OSHI would be nice and simpler. It would possible to add a new function in WmiUtil to execute ASSOCIATORS-queries.

Is that possible in the future ?

**Comment by dbwiddis** [comment]
For the first question, percent: in general we would avoid reporting a percentage in preference to raw values for which the user can do simple math.   For example, we report logical drive usage... total and available, but leave it to the user to divide and format the resulting number.

The example query you gave for usage seems to indicate the amount of time the disk is spinning vs. idle?  If we added that, we'd add the total number of seconds of disk activity (and probably total number of read/write operations, for completeness).   Is that what you're looking for?

The second question looks possible, too, it's more a question of where to report the data.  Should the disk store objects include a list of mounted volumes, or should the file store object list the disk they're on?

**Comment by lundefugl** [comment]
1.) it's not the time, the disk is spinning. 
It's the value, you can find in "Windows Ressource Monitor" for disk access. I think it's the time of read and write data. If the value is 100% then you have no more reserve on the disk. Your system will be slow down on more disk operations.

2.) for us: it does not matter. We need only the link.

**Comment by dbwiddis** [comment]
ignore my interpretation of the stats... what matters is that there's a consistent windows/linux/osx set of "# of reads, seconds per read, bytes per read" stats that we can report (cumulative totals), so I'll work toward that.

**Comment by lundefugl** [comment]
That sounds good.
As long as there is the same information that I see it all right.

Maybe you can nevertheless expand WmiUtil with public ASSOCIATORS-query support. It would be easy to write custom extensions or try something.

**Comment by dbwiddis** [comment]
The last argument of the WMIUtil is passed directly to the query.  I've only been adding on the "WHERE..." clauses but you could put the ASSOCIATORS stuff in there as well.

Current plan:
 - Extend Disk bytes read/written to total reads/writes, bytes read/written, total transfer time
 - Either add a lit of partitions to the disk drives, or add the "owning" drive to the filesystem.

**Comment by dbwiddis** [comment]
Leaning toward a `getPartitions()` command which will return something like the output of Linux `lsblk` command:
```
NAME="sda" MAJ:MIN="8:0" RM="0" SIZE="64G" RO="0" TYPE="disk" MOUNTPOINT=""
NAME="sda1" MAJ:MIN="8:1" RM="0" SIZE="62G" RO="0" TYPE="part" MOUNTPOINT="/"
NAME="sda2" MAJ:MIN="8:2" RM="0" SIZE="1K" RO="0" TYPE="part" MOUNTPOINT=""
NAME="sda5" MAJ:MIN="8:5" RM="0" SIZE="2G" RO="0" TYPE="part" MOUNTPOINT="[SWAP]"
NAME="sr0" MAJ:MIN="11:0" RM="1" SIZE="1024M" RO="0" TYPE="rom" MOUNTPOINT=""
NAME="sr1" MAJ:MIN="11:1" RM="1" SIZE="1024M" RO="0" TYPE="rom" MOUNTPOINT=""
```
The name matches the HWDiskStore, the Mount Point matches the OSFileStore, and the MAJ:MIN is a unique partition ID.  The queries you listed for Windows also id's the disk #/partition# (hopefully I can find size info), and for OSX we'd parse this:
```
$ diskutil list
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *960.2 GB   disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:                  Apple_HFS Macintosh HD            959.3 GB   disk0s2
/dev/disk1 (disk image):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        +960.0 GB   disk1
   1:                        EFI EFI                     209.7 MB   disk1s1
   2:                  Apple_HFS Dropbox                 959.7 GB   disk1s2
```

**Comment by lundefugl** [comment]
Wow - you'r fast. Take your time. ;-)
My feature request was not so urgently. I have a dirty solution and my boss is happy.
I'm starting end of the week in my holidays. Earliest in august I think i have time for testing.

**Comment by dbwiddis** [comment]
Haven't even started coding... that won't happen until the weekend.  Just leaving notes here for myself.  :)

**Comment by dbwiddis** [comment]
First part done in #234.

**Comment by dbwiddis** [comment]
Current testing output showing the 0:0 partition on drive 0 mapped to C:\ on Windows:
```
Disks:
 \\.\PHYSICALDRIVE0: (model: Windows 7-0 ATA Device (Standard disk drives) - S/N: 1ACA4T5WH3MDEFMY8AJ4) size: 68.7 GB, reads: 39280 (1.3 GiB), writes: 31324 (445.3 MiB), xfer: 45010 ms
 |-- Disk #0, Partition #0: Installable File System (Installable File System) Maj:Min=0:0, size: 68.7 GB @ C:\
File System:
 File Descriptors: 0/0
 Local Fixed Disk (C:) (Fixed drive) [NTFS] 34.6 GiB of 64.0 GiB free (54.1%) is \\?\Volume{15de1742-988e-11e1-a39a-806e6f6e6963}\ and is mounted at C:\
 3 1/2 Inch Floppy Drive (A:) (Removable drive) [FAT] 1.1 MiB of 1.4 MiB free (82.4%) is \\?\Volume{15de1746-988e-11e1-a39a-806e6f6e6963}\ and is mounted at A:\
 CD-ROM Disc (D:) (CD-ROM) [] 0 bytes of 0 bytes free (NaN%) is \\?\Volume{4f5464ce-a009-11e1-8006-806e6f6e6963}\ and is mounted at D:\
```
Here's the OS X output:
```
Disks:
 disk0: (model: SanDisk Ultra II 960GB - S/N: 161008800550) size: 960.2 GB, reads: 1053132 (23.0 GiB), writes: 243792 (11.1 GiB), xfer: 73424854 ms
 |-- disk0s1: EFI (EFI System Partition) Maj:Min=1:1, size: 209.7 MB
 |-- disk0s2: Macintosh HD (Macintosh SSD) Maj:Min=1:2, size: 959.3 GB @ /
 disk1: (model: Disk Image - S/N: ) size: 960.0 GB, reads: 3678 (60.0 MiB), writes: 281 (8.6 MiB), xfer: 213627 ms
 |-- disk1s1: EFI (EFI System Partition) Maj:Min=1:4, size: 209.7 MB
 |-- disk1s2: Dropbox (disk image) Maj:Min=1:5, size: 959.7 GB @ /Volumes/Dropbox
 disk3: (model: Disk Image - S/N: ) size: 5.8 TB, reads: 20370 (1.3 GiB), writes: 13311 (467.5 MiB), xfer: 9519128934 ms
 |-- disk3s1: EFI (EFI System Partition) Maj:Min=1:8, size: 209.7 MB
 |-- disk3s2: Time Machine Backups (disk image) Maj:Min=1:9, size: 5.8 TB @ /Volumes/Time Machine Backups
File System:
 File Descriptors: 5011/12288
 Macintosh HD (Volume) [hfs] 353.2 GiB of 893.5 GiB free (39.5%) is /dev/disk0s2 and is mounted at /
 Dropbox (Volume) [hfs] 353.2 GiB of 893.7 GiB free (39.5%) is /dev/disk1s2 and is mounted at /Volumes/Dropbox
 Time Machine Backups (Volume) [hfs] 4.5 TiB of 5.3 TiB free (84.6%) is /dev/disk3s2 and is mounted at /Volumes/Time Machine Backups
```

**Comment by dbwiddis** [comment]
Linux:
```
Disks:
 /dev/sda: (model: Ubuntu_Linux-0 - S/N: XQ1PCFXNN6YMN4JDF120) size: 68.7 GB, reads: 67066 (922.9 MiB), writes: 5344 (226.3 MiB), xfer: 17564 ms
 |-- /dev/sda1: sda1 (ext4) Maj:Min=8:1, size: 66.6 GB @ /
 |-- /dev/sda2: sda2 (partition) Maj:Min=8:2, size: 1.0 KB
 |-- /dev/sda5: sda5 (swap) Maj:Min=8:5, size: 2.1 GB
 /dev/sr0: (model: Virtual_DVD-ROM__1_ - S/N: -_31415B265) size: 1.1 GB, reads: ? (?), writes: ? (?), xfer: ? ms
 /dev/sr1: (model: Virtual_DVD-ROM__2_ - S/N: -_31415C265) size: 1.1 GB, reads: ? (?), writes: ? (?), xfer: ? ms
File System:
 File Descriptors: 6528/201127
 / (Local Disk) [ext4] 51.0 GiB of 60.9 GiB free (83.7%) is /dev/sda1 and is mounted at /
```
FreeBSD:
```
Disks:
 ada0: (model: FreeBSD-0 SSD - S/N: P67WZ6W4SMH4H1F42A3H) size: 68.7 GB, reads: 7976 (213.2 MiB), writes: 524 (13.0 MiB), xfer: 1400 ms
 |-- ada0p1: ada0p1 (freebsd-boot) Maj:Min=0:84, size: 524.3 KB
 |-- ada0p2: ada0p2 (freebsd-ufs) Maj:Min=0:86, size: 65.5 GB @ /
 |-- ada0p3: ada0p3 (freebsd-swap) Maj:Min=0:88, size: 3.2 GB
 cd0: (model: Virtual DVD-ROM - S/N: ) size: 729.8 MB, reads: 102 (248.5 KiB), writes: 0 (0 bytes), xfer: 0 ms
File System:
 File Descriptors: 820/64753
 ada0p2 (Local Disk) [ufs] 48.8 GiB of 59.1 GiB free (82.7%) is /dev/ada0p2 and is mounted at /
 10_3_RELEASE_AMD64_CD (Local Disk) [cd9660] 0 bytes of 695.7 MiB free (0.0%) is /dev/cd0 and is mounted at /media/10_3_RELEASE_AMD64_CD
```
Solaris is proving to be a bit more of a challenge...

**Comment by dbwiddis** [comment]
Implemented in #235

**Comment by lundefugl** [comment]
I have test it. It works. Thank you.

On Windows the precision of the transferTime (and the read/writeBytes) is not so good if i calculate a "percent" value or a "bytes per second" value. (I get access values of 140%, which is obviously not useful)
As base I use my own time. For correct calculation would have use the "Timestamp_Sys100NS" value of the "Win32_PerfRawData_PerfDisk_PhysicalDisk".  

Is it possible to add a timestamp value (when the information was generated) to all OSHI data structures ? On systems, without this information, you can add the current system timestamp, when you triggered the detection.

**Comment by dbwiddis** [comment]
The precision is probably fine... for cross-platform I just use milliseconds rather than 100-NS.   But the problem is that you don't know exactly when the data was recorded. Particularly with disks, which have potentially high latency, you're stuck with a "before" or "after" timestamp without really knowing the middle time.

Adding a timestamp is a great idea.  I've added issue #241 to track it.

Out of curiosity, are you using another library to record/track these numbers?  I've been looking at the metrics library as a potential integration to help do some of the math associated with load percentages and the like.

**Comment by lundefugl** [comment]
We don't use another library. We have tested some, but your library is the best.
We use it in a own diagnostic tool which we use at our customers.

**Comment by dbwiddis** [comment]
Latest snapshot includes the timestamps.  Still writing tests, etc., all future comments in #241.
