### ISSUE TITLE
Add timestamp field for counter-type information

### ISSUE THREAD

**Issue by dbwiddis** [dblock/oshi#241]
Rather than return load/usage values, OSHI provides monotonically increasing counters, relying on the user to measure the difference over time to calculate usage.  However, the user's timestamp, taken either before or after retrieving the data, is less accurate than one that could be provided by OSHI at the moment of the data snapshot.

In many cases, such as WMI or kstat, the operating system itself stores a timestamp.

Timestamps should be added to:

- cpu ticks (system, processor, process)
- disk usage (reads/writes/xfer time)
- network usage (reads/writes/bytes)

**Comment by dbwiddis** [comment]
#244 adds to disk and network.   Not needed for cpu ticks as the percentages are based on total tick calculations regardless of time; and process already enables the calculation with the uptime field (timestamp = start time + up time if needed).

**Comment by lundefugl** [comment]
It works perfect. 
Many many thanks.
