### ISSUE TITLE
Calculate the difference of internal int values

### ISSUE THREAD

**Issue by lundefugl** [dblock/oshi#242]
Sorry - I have a new problem.

I reading the receive/send byte values from the network interfaces.
It workes, but to calculate the difference is not working correct. The problem is the source of the values. It's in `IPHlpAPI` as a `int`.
On the external interface it's a `long`. On wrap arounds of the `int` value (on gigabit networks very offen) the difference calculation generates negative or very high results.

Do you have a idea how to calculate the difference correct ?

**Comment by lundefugl** [comment]
It's very dubious.
On the system I have very low network traffic (TaskManager 0% ... 0.01%).

First call to readBytes returnes -1605051343.
After 3 seconds it returnes -1605055589.
The value is less than the previous value.

**Comment by dbwiddis** [comment]
#243 Switches the network stats to 64-bit.  Let me know if the current SNAPSHOT fixes your issues.

**Comment by lundefugl** [comment]
It works perfect. 
Many many thanks.
