### ISSUE TITLE
Version in pom.xml for v1.2

### ISSUE THREAD

**Issue by alessiofachechi** [dblock/oshi#35]
@dbwiddis probably you forget to set in `pom.xml` of the tag v1.2 (and of the master) the version at 1.2.

**Comment by dbwiddis** [comment]
I didn't forget to set it, so much as forget to commit it.  :wink: 

But seriously -- I've made many more changes than the version tag in that file, and have a few more I need to make that have to do with publishing to the Central Repository, which unfortunately requires a 2 business day wait the first time to get the project set up.

It's updated properly in the zipped release.   And when I do finally update it, I think it should actually be set for the next version (possibly with the -SNAPSHOT appended.)

I'm still learning Maven. If you know more and would like to teach me, please do so!

**Comment by dbwiddis** [comment]
https://issues.sonatype.org/browse/OSSRH-16053

**Comment by dbwiddis** [comment]
OK!  Merged #36. It's now 1.2.1-SNAPSHOT, and you can see all the other pom.xml changes I made to get us [published on the Central Repository (a.k.a. Maven Central)](https://oss.sonatype.org/content/repositories/releases/com/github/dblock/oshi-core/1.2/).   A few bumps in this release road but the next release should be a lot more smooth.

**Comment by alessiofachechi** [comment]
Well done @dbwiddis! :+1: :)

Anyway I know only the M2 basics, so I couldn't help you so much... :stuck_out_tongue_winking_eye:
