### ISSUE TITLE
Javadocs

### ISSUE THREAD

**Issue by dbwiddis** [dblock/oshi#37]
So, part of packaging the release produced a lovely `/target/apidocs` folder with all our current javadocs.

Should I upload the apidocs folder to the project root and link to it from the README?  Or do we have a better system for hosting our javadocs?   Speaking of which, they could use an overhaul to add a lot of detail.  They're pretty minimal.

**Comment by dbwiddis** [comment]
This looks like a possible place to host docs, and have them built with every commit...

**Comment by dbwiddis** [comment]
Apparently the gh-pages branch is special and serves html files.  Copying the apidocs folder to that branch works great, and it's linked from the README with #40.

**Comment by hazendaz** [comment]
gh-pages is primed and ready to go with PR #41 After merging that, simply 'run mvn site' and give the site page a look.  If ok at that point, then perform 'mvn site:deploy'.

**Comment by hazendaz** [comment]
There is an eclipse plugin called jautodoc.  It might be useful to use that to build out all javadocs in case any are missing.  Then we should perform a build with jdk8 to ensure it builds javadocs without failure.

**Comment by dbwiddis** [comment]
Thanks for the recommendation. I've been manually going through the javadocs (I have the non-platform specific ones done) but would be great to auto-fill all the `{@inheritDoc}`s!

**Comment by hazendaz** [comment]
I'm pushing a PR now that has auto doc'd the few remaining plus added missing package-info.java files.  This is pretty clean so I'll merge in.  Next up I'm performing some language cleanups and best practices.  That later set of changes is intrusive so I'll leave it for comment.
