### ISSUE TITLE
Download from Maven Central only

### ISSUE THREAD

**Issue by dblock** [dblock/oshi#39]
I wonder whether the download links should be only from maven central and the "releases" deleted on Github. This might "simplify" the release process.

**Comment by dbwiddis** [comment]
The release to zip the current download is a single command line, file rename, and drag-and-drop upload along with the version tag on github.  Hardly a challenge to complete!  

That said, if there are other benefits to pointing to the maven central download, it may be easier to just link there.  I'll let you make this call...

**Comment by dblock** [comment]
I don't have a strong preference!

**Comment by dbwiddis** [comment]
The advantage of the zip file is that it includes both the jar(s, including dependencies) and javadoc and is a one-click download.

On Maven, we would have our choice of links:
* The overall project: http://search.maven.org/#browse%7C-623552688 (Advantage: link never changes. They can pick version.)
* The current version, that we'd update the link at release time: http://search.maven.org/#browse%7C919611498 or, I prefer http://search.maven.org/#artifactdetails|com.github.dblock|oshi-core|1.2| (Advantage: checksums, etc. for those who care. One link for all the files. Dependency info for multiple systems, not only maven.)
* Each individual jar file: http://search.maven.org/remotecontent?filepath=com/github/dblock/oshi-core/1.2/oshi-core-1.2.jar (Advantage: direct download. Disadvantage: need to link multiple files.)

I like that second "current version" link and want to include it in any case:
* Predictable URL to proactively change even before release, multiple dependency options, fewer jar file links.

And we don't need the javadocs if we can get them on the site (see #37).

So, let's move toward [this link](http://search.maven.org/#artifactdetails|com.github.dblock|oshi-core|1.2|) with javadocs on the site.

**Comment by dblock** [comment]
:+1:

**Comment by dbwiddis** [comment]
As of #40, set download link to maven central. Also added a "badge" for maven central that goes to the same place.  Doesn't hurt to add the zipfile with the release tag and takes so little time it's probably worth it, so I left that zipfile uploading in the RELEASING document so it will be available from the github "releases" menu option.
