### ISSUE TITLE
Update Maven Build to be similar with Waffle (another dblock project)

### ISSUE THREAD

**Issue by hazendaz** [dblock/oshi#42]
Bring maven up to spec with current dblock waffle project.  This will make a lot of things easy.  See PR #41

**Comment by hazendaz** [comment]
I think to get this we do a few things first.

1) My current PR is more of just a overall final goal.
2) We bump jna to 4.1.0 along with junit to 4.12
3) We bump to java 1.6
4) Add any magic you wanted with java 1.6 per #28 info.
5) Bring in the entire new pom structure
6) Release gh-pages
7) Release project as 1.3.0 as java requirment and jna are updated verifiying everything works.
8) Then move forwards with jdk7.

**Comment by dbwiddis** [comment]
My take:
1) Good overall goal.
2) Jna to 4.1.0 along with junit to 4.12 - done
2a) I've submitted a change to JNA for the SystemB class, and want to rewrite our code here to match, so that when 4.2.0 is released, I can just point the package there. Key difference is removing the hardcoded constants for `sysctl()` and using `sysctlbyname()` instead (more robust to unlikely, but possible, enum changes.)
3) We bump to java 1.7.  (Filesystem and CPU stuff is too much hacking and commandline parsing without 1.7 methods.)
4) Add magic with java 1.7 per #28 info and #38 (without breaking API).
5) Bring in the entire new pom structure
6) Release gh-pages
7) Release project as 1.3.0 as java requirment and jna are updated verifiying everything works.
8) Consider API-breaking refactoring per #46 as new features are developed.

**Comment by dbwiddis** [comment]
1, 2(not 2a), 3, 4, 5 done.
6 - @hazendaz on the hook to do gh-pages release with new pom magic and document
7 - once we've handled any outstanding issues with current project setup, we release 1.3
8 and 2a - On back burner for 2.0, pending a few more plans that may be 1.4 (per-core measures).

**Comment by hazendaz** [comment]
@dblock is JNA 4.2.0 coming soon?  Guess it's been just over a year there and this particular project is certainly on a roll so if we could get that it would be great!

**Comment by dbwiddis** [comment]
Still having problems with my build on the `license-maven-plugin`.  First issue is that it can't parse the version... I think there's a stray `]` in `[2.11,)]`.

Fixing that, the next problem is: `Duplicated tag: 'pluginExecutionFilter'`.  I added tags to close and reopen `<pluginExecution>` just below that version.  Then I get back to the original error: "Plugin execution not covered by lifecycle configuration: com.mycila:license-maven-plugin:2.11:format (execution: default, phase: compile)".

I marked it as ignored in Eclipse and it looks like it's working now....

**Comment by hazendaz** [comment]
Arrggghh…I’ve done that too many times.  I tried to add that manually rather than letting it add automatically as it won’t add under the profile otherwise.  I did put a fix in there and merged it in just now (still a minor mistake but got error back).  The only way for you to check that now is to delete the overall eclipse one you likely have in place now ignoring it.  If you go into maven settings, it is listed in there somewhere.  There is a master XML file that will list the license plugin if ignored that way.

 

I had the goal wrong too so that is coming in now.

**Comment by dblock** [comment]
I am not sure about JNA, @twall can comment.

**Comment by dbwiddis** [comment]
I've finished enough code that I went to try to release 1.3, but didn't get very far.  My first step, `mvn site` encounters multiple errors, takes almost 2 hours, and eventually fails on a lack of PermGen space.  Stack trace on the failure which may or may not help:
```
java.lang.OutOfMemoryError: PermGen space
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(ClassRealm.java:389)
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:235)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
	at org.apache.velocity.runtime.parser.Parser.<init>(Parser.java:3497)
	at org.apache.velocity.runtime.parser.Parser.<init>(Parser.java:64)
	at org.apache.velocity.runtime.RuntimeInstance.createNewParser(RuntimeInstance.java:1130)
	at org.apache.velocity.runtime.ParserPoolImpl.initialize(ParserPoolImpl.java:50)
	at org.apache.velocity.runtime.RuntimeInstance.initializeParserPool(RuntimeInstance.java:1103)
	at org.apache.velocity.runtime.RuntimeInstance.init(RuntimeInstance.java:266)
	at org.apache.velocity.app.VelocityEngine.init(VelocityEngine.java:93)
	at org.owasp.dependencycheck.reporting.ReportGenerator.<init>(ReportGenerator.java:100)
	at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.writeReports(BaseDependencyCheckMojo.java:821)
	at org.owasp.dependencycheck.maven.AggregateMojo.runCheck(AggregateMojo.java:117)
	at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.generate(BaseDependencyCheckMojo.java:406)
	at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.generate(BaseDependencyCheckMojo.java:388)
	at org.apache.maven.plugins.site.render.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:233)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:311)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:129)
	at org.apache.maven.plugins.site.render.SiteMojo.renderLocale(SiteMojo.java:182)
	at org.apache.maven.plugins.site.render.SiteMojo.execute(SiteMojo.java:141)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
```

**Comment by KVqVuo6Z** [comment]
Maybe the fix described here might help: http://stackoverflow.com/questions/3101128/java-lang-outofmemoryerror-permgen-space-in-maven-build?

**Comment by dbwiddis** [comment]
Looks like I can set an environment varialbe as a quick fix, but the `pom.xml` will need updating for the compiler to use it more permanently, I think.  (It appears I max out at 64MB.)

**Comment by hazendaz** [comment]
Timings I'm getting....I did get a strange failure when running mvn clean install once.  It failed but then worked after that.  Not exactly sure why or if that is repeatable.

I'd suggest running command line to do these sort of things in case you are not...

mvn clean install ~17 seconds
mvn site ~1 min 33 seconds
mvn site:deploy ~14 seconds

Nothing magical there.  Those were the commands.  I actually used posh git (from windows for github) to run this.  If you check, the site is released now.

**Comment by dbwiddis** [comment]
I am running commandline, but unfortunately on my own fork rather than the main project, so while I got `mvn site` to work by increasing permgen space, my attempt to `mvn site:deploy` failed on some sort of credential error on the dblock site.

**Comment by hazendaz** [comment]
The site is based on the pom contents so it's never actually on your fork but rather on the upstream doing the work.  I did it all from my fork as well.  I wonder if @dblock has something blocked there for you.  Everything should be fairly straight at the moment.  I think if you can handle documentation steps as I outlined what I did, then the two issues can be dropped.  Your PR will need the pom change removed from it as that happens automatically during the release.  Maven release plugin helps us out there.  There is an issue in the assembly file as it is very linux based.  I have seen that before and it's easy to cleanup.  When I get a little more time, I'll fix that.

**Comment by dbwiddis** [comment]
updated my PR to remove the pom change.

**Comment by dbwiddis** [comment]
The links to the files/diffs from the auto-generated changelog don't work.

They start with https://github.com/dblock/oshi.git/src/ .... they should start with https://github.com/dblock/tree/master/src/

Is that something we can change in our pom, or site setup, or is the plugin broken?

**Comment by dbwiddis** [comment]
Just noticed a stray Waffle in the pom.xml distributionManagement section.

**Comment by hazendaz** [comment]
Plugin is probably broken.  Maven team is working on getting things working.  I'll report the issue


Sent by Outlook for Android





On Sun, Jun 28, 2015 at 9:26 PM -0700, "dbwiddis" <notifications@github.com> wrote:
The links to the files/diffs from the auto-generated changelog don't work.

They start with https://github.com/dblock/oshi.git/src/ .... they should start with https://github.com/dblock/tree/master/src/

Is that something we can change in our pom, or site setup, or is the plugin broken?

---

**Comment by hazendaz** [comment]
Good catch.  I found a small formatting issue in pom too.  If you get to this first, the formatting issue is near scm...


Sent by Outlook for Android





On Sun, Jun 28, 2015 at 10:23 PM -0700, "dbwiddis" <notifications@github.com> wrote:
Just noticed a stray Waffle in the pom.xml distributionManagement section.

---

**Comment by dbwiddis** [comment]
I think we've mostly done this!  Thanks for all the help @hazendaz

**Comment by hazendaz** [comment]
Wow you have been busy!  Nice job on the release.

 

Jeremy

**Comment by dbwiddis** [comment]
A few speed bumps figuring things out but I think I got it.  Still doesn't show up in some searches but I'm hoping we just have to wait on that....

**Comment by dbwiddis** [comment]
I'm going to reopen this with a few questions prompted from today's release process that didn't quite go as smoothly as it will the next time... with an eye on making it easier for the Next Guy (tm).

* While the maven release:perform command published to the staging repository, I had to log in to Nexus to manually release it.  The directions [here](http://central.sonatype.org/pages/releasing-the-deployment.html) indicate that this process can be automated (last paragraph).   However, I think it's a good idea to require that manual release step, and have documented it.
* The build failed the first time due to some javadoc issues, and getting it started back up was kind of a pain because of its partially built state, doing more commits, etc.  I think we should do "mvn -DdryRun=true release:prepare" before the actual prepare step, to catch errors like this without actually modifying anything.  Do you concur?

**Comment by hazendaz** [comment]
I agree.  I didn't know about dryRun and have always hated it when things didn't go right.  In some cases, I've bumped libraries up due to failed attempts.  Definitely put that in the documentation :)

**Comment by dbwiddis** [comment]
OK, updated the releasing doc.  And all the search, etc. looks caught up!  Woohoo!
