### ISSUE TITLE
Drop java 1.5 support

### ISSUE THREAD

**Issue by hazendaz** [dblock/oshi#43]
Java 1.5 is EOL
Java 1.6 is EOL
Java 1.7 is EOL

So drop 5 already.  It's pretty doubtful anyone is still using 5 by 2015.  Java 6 will linger for some time but at least will allow some other features to be added.  Java 7 is mostly unnecessary.  If this project ultimately needs that, it would be better to jump to 8 where the real possiblities are.  However, that jump might be too high for most users.

Jump to 1.6 is on PR #41

**Comment by dbwiddis** [comment]
I'm already planning on 1.7 as part of #28.

**Comment by dbwiddis** [comment]
1.7 enables access to improved OperatingSystemMXBean methods and a "read-the-whole-file" replacement for our current FileUtil, well worth moving from 6 to 7.  And we aren't using anything from 8 yet....

**Comment by hazendaz** [comment]
I say for time being while working that out, we move to 1.6 for starters.  Then go from there.  I know at my day job, we still have a good mix of java 6 and 7.  However, we are fast approaching having everything in java 7.  While this project probably has a smaller community of users, I think moving to java 6 for a bit is a good thing.  If you want to move faster to 7, that is cool too.  I wasn't even aware of this until Db poionted it out.  I'm thinking this might be a project I will want to pick up for psi-probe project that I have been committing on, if not on other projects.  It seems pretty cool.

**Comment by dbwiddis** [comment]
Having spent a day banging my head against the wall doing stuff with filesystems that the java.nio.file classes made trivial, I'm waving the 1.7 flag frantically.  If you want to do 1.6 to keep your conscience clear and then let me do 1.7 the next day, that's fine.  Just sayin'.

**Comment by dbwiddis** [comment]
Updated to 1.7 as part of #50

**Comment by hazendaz** [comment]
Well this usually never happens.  Looks like we are both active at the same time.  If you see this, can you hold up a few so I can get properly rebased then we can get my stuff in as well :)
