### ISSUE TITLE
ghpages push

### ISSUE THREAD

**Issue by hazendaz** [dblock/oshi#44]
PR #41 is primed for pushing to ghpages.  The layout is bootstrapped so it has a nice look and feel.  It's otherwise pretty basic in layout.  Once ghpages is done, should add a link off README pointing there thus making it easier to find.

**Comment by dbwiddis** [comment]
I have updated the README with the existing link to gh_pages that I created manually, probably working in parallel with #41.  I assume the new layout will simply overwrite what I've done?

**Comment by hazendaz** [comment]
New layout will overlay the manual push you made.  It will still retain commit history in ghpages as does any other branch.

**Comment by hazendaz** [comment]
I have pushed gh-pages out.  The apidocs are still in correct location and in fact are the newly pushed ghpages cut of 1.3-snapshot.  I'll add a link to site directly from README and get some documents created going forward once I get some time.  For now, closing this out as completed.
