### ISSUE TITLE
Changelog - is that necessary?

### ISSUE THREAD

**Issue by hazendaz** [dblock/oshi#45]
With maven updates on #41, changelog is part of the site generation.  It's automated and currently set to default (ie month interval).  Given that it is much nicer than what we can otherwise generate by hand, is changelog really necessary now?  Review ghpages once available and make a determination.

**Comment by dbwiddis** [comment]
I'll look once it's up... does it credit the author of changes?

**Comment by hazendaz** [comment]
Yes, it does credit the authors.  The only real question is do we care about historical change logis as this is just a view into the change history.  It produces 3 variations of the report.  Initially I have it defaulted so it is just a month.  We may need to make a schedule for releases.  There is really nothing wrong with doing that.  So say we release a new version once a month and then product the site page.  It will show the activities during that time.

**Comment by dblock** [comment]
Personally I like manual CHANGELOGs because they are done manually, ie. humans do a good job curating the actual list of changes. Machine made changelogs out of commits or PRs are OK, but they are hard to grok.

**Comment by hazendaz** [comment]
I'm with you.  The more I thought about this the more I realized we would only get a time period on each site generation and some folks would want historical depending on their upgrade path.  So maybe we just list major items users would care about rather than trivial changes.

--- Original Message ---

**Comment by hazendaz** [comment]
How about this approach.  Currently I see us always putting in the PR information to the change log.  While that all seems fine, a lot of times it is after the fact and/or ends up being slightly off.  On PR #41, I added the bulk of new changes without mention of the individual PR entries for this reason.  I added a note to check out site page for actual PR information as automation there will help save fixes to changelog.  If we take that one step forward and add the link to the site page once it's live and available, I think we will still get what we need, more or less.  Only thing I don't quite know yet is dealing with historical site information as that change log isn't exactly GIT enabled other than it shows a time period of all activity and does a good job of breaking down whom did what.

**Comment by dbwiddis** [comment]
I think there's way too much info in the Changelog from #41.  It's got a lot of the little things that we wanted to avoid cluttering.  I would summarize it all in "Updated POM to best practices from waffle project." or something like that.  With a link to the github PR, which links to Issues in which these are discussed, plus the diffs, I think there's plenty of information for anyone to dissect individual changes.

This is all a moot point because soon the project will be perfect and we will have no more changes. :stuck_out_tongue_winking_eye:

**Comment by hazendaz** [comment]
I probably did go overboard there.  Users probably could care less about our build.  If you haven't beat me to it I can get that resolved while looking at other issues.  Thanks

--- Original Message ---

**Comment by dbwiddis** [comment]
I'm done for a while... at least until you get all the new stuff you 
uploaded working nicely.

**Comment by hazendaz** [comment]
The change log has been cleaned up and will come into fold in a few minutes.
