### ISSUE TITLE
Raspberry Pi - Exception

### ISSUE THREAD

**Issue by MahatmaX** [dblock/oshi#79]
Hi,
I do not expect a Raspberry Pi to be supported, but for the sake of completeness, here is an Exception that is thrown:

 Exception in thread "Timer-12" java.lang.IllegalArgumentException: Processor number (0) must be less than the number of CPUs: 0
     [java]     at oshi.software.os.linux.proc.CentralProcessor.<init>(CentralProcessor.java:107)
     [java]     at oshi.software.os.linux.LinuxHardwareAbstractionLayer.getProcessors(LinuxHardwareAbstractionLayer.java:78)
     [java]     at de.jespa.clients.systeminfo.SystemInfoAgent.getSystemInfo(SystemInfoAgent.java:152)
     [java]     at de.jespa.clients.systeminfo.SystemInfoAgent.publishEvent(SystemInfoAgent.java:133)
     [java]     at de.jespa.clients.systeminfo.SystemInfoAgent.access$300(SystemInfoAgent.java:39)
     [java]     at de.jespa.clients.systeminfo.SystemInfoAgent$2$1.run(SystemInfoAgent.java:108)
     [java]     at java.util.TimerThread.mainLoop(Timer.java:555)
     [java]     at java.util.TimerThread.run(Timer.java:505)

Cheers Dirk

**Comment by dbwiddis** [comment]
I believe this exception was reported in #70 and fixed (yesterday) in #76.

For confirmation, could you post the output of "cat /proc/cpuinfo" on Raspberry Pi?  (It probably excludes the "core id" field but I want to confirm it contains the "processor" field.)

**Comment by MahatmaX** [comment]
Sorry, I did not match mine and the other issue. And yes, that probably is the same issue. The output of my cpuinfo looks like:

processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 2.00
Features        : half thumb fastmult vfp edsp java tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2708
Revision        : 0010
Serial          : 00000000af918ac3

**Comment by dbwiddis** [comment]
Yep, same issue. I've switched it to parse "processor" instead of "cpu info" (fixes your specific error) and threw in a minimum 1 CPU just in case.  Should resolve this.
