### ISSUE TITLE
Sonatype parent is now deprecated - use directly

### ISSUE THREAD

**Issue by hazendaz** [dblock/oshi#85]
Sonatype deprecated the oss parent some time ago and I just ran across this today when pushing out waffle.  The obvious thing was during the release it was dropping back to old plugin versions and ultimately failing for various reasons.  The documentation from sonatype isn't exactly perfect.  Ultimately it's a minor change with the final 'mvn release:perform -Prelease' being used.  Look at this commit over on my base parent for the shorter way to make this work.  It does include some extra things for site generation which I think are already here. If not, those should be applied as well.

https://github.com/hazendaz/base-parent/commit/6dd8fa370954a568c5b262bfcfe5a998e1eb6c3b

**Comment by dbwiddis** [comment]
Does this need to be fixed before I can push the next release?

**Comment by dbwiddis** [comment]
In my research on trying to push out a snapshot I think you're not supposed to use the same id for snapshot and release repos....

**Comment by dbwiddis** [comment]
Took care of this, and managed a snapshot release, too!

**Comment by hazendaz** [comment]
Cool.  Good little win.


Sent by Outlook for Android





On Sat, Sep 19, 2015 at 9:50 PM -0700, "dbwiddis" <notifications@github.com> wrote:
Closed #85.

---
Reply to this email directly or view it on GitHub:
https://github.com/dblock/oshi/issues/85#event-414080057

**Comment by dbwiddis** [comment]
FYI, I hooked up our repository to [VersionEye](https://www.versioneye.com/user/projects/55fed58c601dd9001500005e) and found several out of date plugins in the pom that I've updated. You might consider doing the same.

**Comment by hazendaz** [comment]
Thanks.  I usually do this manually (mvn site – version report) but automation is so much better.  I’m tying waffle in now.

 

Thanks,

 

Jeremy

**Comment by hazendaz** [comment]
I’ve hooked this up to a number of repos now.  Thanks for pointing this one out.  It seems there is a place for both maven version and this as they both come up with somewhat different results in some cases.

 

Jeremy

 

From: Jeremy Landis [mailto:jeremylandis@hotmail.com] 
Sent: Sunday, September 20, 2015 6:43 PM
To: 'dblock/oshi' <reply@reply.github.com>; 'dblock/oshi' <oshi@noreply.github.com>
Subject: RE: [oshi] Sonatype parent is now deprecated - use directly (#85)

 

Thanks.  I usually do this manually (mvn site – version report) but automation is so much better.  I’m tying waffle in now.

 

Thanks,

 

Jeremy

**Comment by dbwiddis** [comment]
Yeah... and sometimes not accurate... the maven-release-plugin version (3.0-r1585899) is not available if you try to use it, 2.5.2 is the latest there.  But it's something, at least. And one more little badge to put on the front page. :)

**Comment by hazendaz** [comment]
I'm guessing that 3.0-rxxx was something maven did when going to maven 3 years ago.  My work repos come up with that one but maven central does not.  So unsure what repo this is tied into bug clearly that one is wrong so I've been muting that one.

**Comment by dbwiddis** [comment]
It got a lot more complex than that, eventually.

I tried to push a release today and had quite a few ssh errors with a known-host issue, that reverting the jgit and wagon/wagon-ssh versions fixed.  And then it wasn't getting signed properly because i didn't have the appropriate configuration for auto-signing copied over from the OSS parent.

Got it working to release, but wouldn't mind a once-over to see if I've done something wrong (do I need versions twice, etc.)

**Comment by hazendaz** [comment]
I think there is a bug in the git site push for 2.0.4 version.  I've got an open ticket on that which the product owner put out a 2.0.5-SNAPSHOT.  Now I get a readible error.  I'm still investigating that.  I think wagon 2.10 though is ok.  I'm looking over some things in the library for some minor cleanups.  I have eclipse complaining about pretty much everything so I'll do a PR for some of this shortly.  Although off topic here, I would highly consider a one time switch from tabs to spaces against the library.  If you want that, if you want that we can quickly add a formater to enforce the coding style.

**Comment by hazendaz** [comment]
I see the formatter is in the pom.  It's just not activated currently.

**Comment by dbwiddis** [comment]
I suggested the spaces when doing the Eclipse Mars reformatting.  I can make that happen.  2 or 4 spaces per tab?

**Comment by dbwiddis** [comment]
Other pom changes: I think there's a duplicate section for gpg... the one I had in there manually and the second one recently copied from the parent to make it work.  I think I can delete the first one.  Wagon 2.10 may be ok, I just reverted both wagon things for troubleshooting and stopped when it worked...  I think 2.0.4 added ssh-agent capability that may be messing with things (causing the very bug that it was trying to fix).

**Comment by hazendaz** [comment]
I personally like 4 spaces and we can use my own build-tools which I recently added to waffle.  It's quick and easy but will need done completely separate.  I'll add the format file with -temp on it so when we are ready we just remove -temp and let it fly then merge it in.  It will affect all files.  It doesn't handle xml but at least deals with the java code.

Yes, that jgit ssh stuff is what is causing issue.  Once I figure out the core issue, I'll share the info.

**Comment by dbwiddis** [comment]
I can do it in Eclipse in a few clicks, and save the files so others using Eclipse can use the same formatting.  I'll do that sometime tonight.  Then your format file can catch anything the Eclipse reformat missed.
