### ISSUE TITLE
Add Logging Capability

### ISSUE THREAD

**Issue by dbwiddis** [dblock/oshi#88]
We should consider adding a logging capability

Pros:
- lightweight
- makes it easier for developers and users to debug errors (especially if we're suppressing exceptions on initialization, such as addressing #86)
- assists in self-documenting code

Cons:
- requires another dependency unless we use JUL
- requires choice of which framework to use
- requires users to handle the log output

While I'm partial to log4j2, it's probably overkill and introduces a requirement for a config file.  I think just using slf4j-simple will suffice for this project and require no extra config.

**Comment by dbwiddis** [comment]
Adding this to the #87 PR (but a second commit) as part of a complete solution to get rid of throwing exceptions throughout the code, replacing them with log errors/warnings/methods to access.

adding slf4j-api as dependency on main project and slf4j-simple within test scope.

**Comment by hazendaz** [comment]
Slf4j api is king.  It doesn't log on its own so users get to choose their logging.  +1 on slf4j api with simple for testing.


Sent by Outlook for Android





On Sat, Sep 19, 2015 at 12:41 PM -0700, "dbwiddis" <notifications@github.com> wrote:
Adding this to the #87 PR (but a second commit) as part of a complete solution to get rid of throwing exceptions throughout the code, replacing them with log errors/warnings/methods to access.

adding slf4j-api as dependency on main project and slf4j-simple within test scope.

---

**Comment by dbwiddis** [comment]
Done in #87
