### ISSUE TITLE
JNA 4.2

### ISSUE THREAD

**Issue by dbwiddis** [dblock/oshi#93]
JNA 4.2.0 has been released.  This may include some duplication of oshi code that was submitted to JNA as a patch, and should be removed in favor of the upstream dependency.

A complete review of the change log and any other necessary modifications should be conducted.

**Comment by hazendaz** [comment]
Nice long overdue jna


Sent by Outlook for Android





On Mon, Sep 28, 2015 at 11:38 AM -0700, "dbwiddis" <notifications@github.com> wrote:
JNA 4.2.0 has been released.  This may include some duplication of oshi code that was submitted to JNA as a patch, and should be removed in favor of the upstream dependency.

A complete review of the change log and any other necessary modifications should be conducted.

---
Reply to this email directly or view it on GitHub:
https://github.com/dblock/oshi/issues/93

**Comment by dbwiddis** [comment]
And of course I realize that I added a constant and a method after submitting to JNA so we still need a library until I get THAT change into the next JNA...

**Comment by dbwiddis** [comment]
Done in #94.  No other changes needed until 4.2.1...
