### ISSUE TITLE
Expose information about physical vs. logical cpu count (cores vs. threads)

### ISSUE THREAD

**Issue by tfenne** [dblock/oshi#99]
I'd find it really useful to be able to access how many physical CPUs are present as well as how many logical CPUs.  Seems like this should be easy to do, at least for mac and linux (I don't have any recent experience or access to a windows machine, so can't comment on that).

Perhaps the simplest solution would be to add `HardwareAbstractionLayer.getPhysicalProcessorCount()` or `HardwareAbstractionLayer.getThreadsPerCore()`?

I'd be happy to take a shot at a PR that covers mac and linux, given a little feedback on how to integrate this information into the API.

**Comment by dblock** [comment]
Seems like a good feature request, but the language should be clarified. How will this relate to the current `getProcessors`? Adding `getPhysicalProcessors` (count should be `getPhysicalProcessors().count()`?) seems somewhat redundant, should `getProcessors` be extended to take options?

**Comment by dbwiddis** [comment]
Windows is (relatively) easy to count.  We can extend (initially and submit pr to jna) JNA's Kernel32 library for [GetLogicalProcessorInformationEx](https://msdn.microsoft.com/en-us/library/windows/desktop/dd405488(v=vs.85).aspx). That method with a RelationshipType of 3 (RelationProcessorPackage) restricts the results to physical processors. 

@dblock correctly points out, however, that we need to make a fundamental decision of how to return this.  Key questions:
* do we want to try to actually identify which of the `Processor` objects are physical vs. logical (adding a boolean isPhysical to the object)?  This may be possible on Windows (see above) structures and Linux (/proc/cpuinfo contains a "core id" field) but I'm not sure how to do it on OS X (or if it is possible -- but given that we could know the number of CPUs we could just arbitrarily pick the ratio).   
* how do we want to handle virtual machines?  Are all the CPUs there virtual, returning 0 for physical count?  

Two options for implementation:
* Only return the desired processors (physical or "all"): overload getProcessors().  Add a new version that takes a boolean parameter `isPhysical`.  The current version with no arguments would call getProcessors(false) to maintain current behavior.
* Add a boolean to the `Processor` defining whether it is virtual or physical, and always return all processors from `getProcessors()` leaving it to the user to filter out physical ones from that boolean.

I lean toward the second option.

**Comment by dbwiddis** [comment]
After rereading the initial question and doing more research, I actually think @tfenne 's initial proposal for `HardwareAbstractionLayer.getThreadsPerCore()` is probably the best.  Rationale:
- on Mac OS X we can't identify at the processor level which it is, so we'd be making stuff up, so my "second option" above doesn't really work
- presuming the use case for this is primarily obtaining a count, my first option above is a lot of overhead just to get a count.
- getting the count is a quick answer on OS X (sysctl calls) and Linux (/proc/CPUinfo) and Windows (see above link, just count structures returned rather than trying to further parse them).

**Comment by tfenne** [comment]
@dbwiddis I think adding a `getThreadsPerCore()` or similar sounds sensible.  I did the same digging around in `sysctl`'s output and cannot figure out how to determine which of the CPUs presented are logical vs. physical, etc.  And I very much agree that it doesn't make sense to make stuff up just to satisfy an API.

My own use case for this is that I'm building software that tries to schedule a workload on a machine (mac laptops for development, AWS linux instances for deployment) and would am defaulting the available hardware to schedule over based on `HardwareAbstractionLayer.getProcessors().size`, which causes over-scheduling on the macs.  For my purposes just being able to detect the number of physical cores vs. threads would be very helpful.

**Comment by dbwiddis** [comment]
Go for it with `getThreadsPerCore()` either on the hardware abstraction layer or the Processor object (that's yet another thing that may drive a separation of "system" vs. "processor" in the v2.0 API) ... perhaps use the word "System" if you put it on the Processor object to be consistent.

If you want to handle the interface and the Mac (easy sysctl call) and Linux (easy cpuinfo parsing) I'll work on the Windows version.

**Comment by dbwiddis** [comment]
Here's the relevant sysctl calls for OS X... just do a simple division:

     hw.ncpu (DEPRECATED)
             The number of cpus.  It is recommended that you use "hw.physicalcpu" "hw.physicalcpu_max"
             "hw.logicalcpu" or "hw.logicalcpu_max" instead.

     hw.physicalcpu
             The number of physical processors available in the current power management mode.

     hw.physicalcpu_max
             The maximum number of physical processors that could be available this boot.

     hw.logicalcpu
             The number of logical processors available in the current power management mode.

     hw.logicalcpu_max
             The maximum number of logical processors that could be available this boot.

**Comment by dbwiddis** [comment]
For linux, parse /proc/cpuinfo.  
* each 'processor' entry is a logical cpu
* each unique combination of 'physical id' and 'core id' entry is a "physical cpu" 
   * single socket quad-core will have one physical id (0) and 4 core id's (0,1,2,3)
   * dual-socket dual-core will have two physical ids (0,1), each with 2 core id's. (0,1)

**Comment by dbwiddis** [comment]
I just deleted my previous comment.  Linux is a bit more complicated. :)

For linux, parse /proc/cpuinfo.  
* If 'siblings' is present and is equal to 1, this is what you want.  (This may be the case on virtual machines.)  Otherwise...
* If 'siblings' is present and > 1, and If both 'siblings' and 'cpu cores' are present, this is the ratio you want (e.g. siblings = 2 x cpu cores for hyperthreaded systems and siblings = cpu cores without hyperthreading).  Otherwise...
* each 'processor' entry is a logical cpu
* each 'core id' entry (if present) is a physical processor, but may be multiple ones per socket.  Some flavors may have 'cpu number' instead.
* each 'physical id' entry is a socket which may contain multiple cpus that share other resources
   * each unique combination of 'physical id' and 'core id' entry is a "physical cpu" 
      * single socket quad-core will have one physical id and 4 core id's (may not be sequential)
      * dual-socket dual-core will have two physical ids (may not be sequential), each with 2 core id's. (may not be sequential)

**Comment by dbwiddis** [comment]
For Windows, `com.sun.jna.platform.win32.Kernel32` has `GetLogicalProcessorInformation()` method which returns a pointer to an array of `com.sun.jna.platform.win32.WinNT.SYSTEM_LOGICAL_PROCESSOR_INFORMATION` structures documented [here](https://msdn.microsoft.com/en-us/library/windows/desktop/ms686694(v=vs.85).aspx).  

Iterate that array, checking for the case when Relationship = RelationProcessorCore (value=0) and ignoring other cases.  Each of these is a physical CPU.  For this physical CPU, count the number of bits set in the ProcessorMask field.  That is logical CPUs per physical CPU.  (In theory you can stop after finding the first such ratio, assuming all processors are equal.  Or you can increment a logical cpu count by these bits here.)

**Comment by dbwiddis** [comment]
Given that the above 3 methods all actually count logical and pysical CPUs, I think it may be better to just expose those two counts.  I'm going to work on that today.

**Comment by dbwiddis** [comment]
For now, I'm putting `getLogicalProcessorCount()` and `getPhysicalProcessorCount()` on the 'Processor` object.

In v2.0 I'll be separating out system processor (moving most of the current `static` Processor code) and individual processor objects, and these methods will go onto the system version.

**Comment by dbwiddis** [comment]
See PR #100 for implementation and let me know what you think....
